package javax.baja.bacnet.enums;

import java.util.HashMap;
import java.util.logging.Logger;
import javax.baja.bacnet.BacnetConst;
import javax.baja.nre.annotations.NiagaraEnum;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.nre.annotations.Range;
import javax.baja.sys.BFrozenEnum;
import javax.baja.sys.Context;
import javax.baja.sys.InvalidEnumException;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;
import javax.baja.units.BUnit;
import javax.baja.units.UnitDatabase;
import javax.baja.units.UnitException;

@NiagaraType
@NiagaraEnum(
   range = {@Range("squareMeters"), @Range("squareFeet"), @Range("milliamperes"), @Range("amperes"), @Range("ohms"), @Range("volts"), @Range("kilovolts"), @Range("megavolts"), @Range("voltAmperes"), @Range("kilovoltAmperes"), @Range("megavoltAmperes"), @Range("voltAmperesReactive"), @Range("kilovoltAmperesReactive"), @Range("megavoltAmperesReactive"), @Range("degreesPhase"), @Range("powerFactor"), @Range("joules"), @Range("kilojoules"), @Range("wattHours"), @Range("kilowattHours"), @Range("btus"), @Range("therms"), @Range("tonHours"), @Range("joulesPerKilogramDryAir"), @Range("btusPerPoundDryAir"), @Range("cyclesPerHour"), @Range("cyclesPerMinute"), @Range("hertz"), @Range("gramsOfWaterPerKilogramDryAir"), @Range("percentRelativeHumidity"), @Range("millimeters"), @Range("meters"), @Range("inches"), @Range("feet"), @Range("wattsPerSquareFoot"), @Range("wattsPerSquareMeter"), @Range("lumens"), @Range("luxes"), @Range("footCandles"), @Range("kilograms"), @Range("poundsMass"), @Range("tons"), @Range("kilogramsPerSecond"), @Range("kilogramsPerMinute"), @Range("kilogramsPerHour"), @Range("poundsMassPerMinute"), @Range("poundsMassPerHour"), @Range("watts"), @Range("kilowatts"), @Range("megawatts"), @Range("btusPerHour"), @Range("horsepower"), @Range("tonsRefrigeration"), @Range("pascals"), @Range("kilopascals"), @Range("bars"), @Range("poundsForcePerSquareInch"), @Range("centimetersOfWater"), @Range("inchesOfWater"), @Range("millimetersOfMercury"), @Range("centimetersOfMercury"), @Range("inchesOfMercury"), @Range("degreesCelsius"), @Range("degreesKelvin"), @Range("degreesFahrenheit"), @Range("degreeDaysCelsius"), @Range("degreeDaysFahrenheit"), @Range("years"), @Range("months"), @Range("weeks"), @Range("days"), @Range("hours"), @Range("minutes"), @Range("seconds"), @Range("metersPerSecond"), @Range("kilometersPerHour"), @Range("feetPerSecond"), @Range("feetPerMinute"), @Range("milesPerHour"), @Range("cubicFeet"), @Range("cubicMeters"), @Range("imperialGallons"), @Range("liters"), @Range("usGallons"), @Range("cubicFeetPerMinute"), @Range("cubicMetersPerSecond"), @Range("imperialGallonsPerMinute"), @Range("litersPerSecond"), @Range("litersPerMinute"), @Range("usGallonsPerMinute"), @Range("degreesAngular"), @Range("degreesCelsiusPerHour"), @Range("degreesCelsiusPerMinute"), @Range("degreesFahrenheitPerHour"), @Range("degreesFahrenheitPerMinute"), @Range("noUnits"), @Range("partsPerMillion"), @Range("partsPerBillion"), @Range("percent"), @Range("percentPerSecond"), @Range("perMinute"), @Range("perSecond"), @Range("psiPerDegreeFahrenheit"), @Range("radians"), @Range("revolutionsPerMinute"), @Range("currency1"), @Range("currency2"), @Range("currency3"), @Range("currency4"), @Range("currency5"), @Range("currency6"), @Range("currency7"), @Range("currency8"), @Range("currency9"), @Range("currency10"), @Range("squareInches"), @Range("squareCentimeters"), @Range("btusPerPound"), @Range("centimeters"), @Range("poundsMassPerSecond"), @Range("deltaDegreesFahrenheit"), @Range("deltaDegreesKelvin"), @Range("kilohms"), @Range("megohms"), @Range("millivolts"), @Range("kilojoulesPerKilogram"), @Range("megajoules"), @Range("joulesPerDegreeKelvin"), @Range("joulesPerKilogramDegreeKelvin"), @Range("kilohertz"), @Range("megahertz"), @Range("perHour"), @Range("milliwatts"), @Range("hectopascals"), @Range("millibars"), @Range("cubicMetersPerHour"), @Range("litersPerHour"), @Range("kilowattHoursPerSquareMeter"), @Range("kilowattHoursPerSquareFoot"), @Range("megajoulesPerSquareMeter"), @Range("megajoulesPerSquareFoot"), @Range("wattsPerSquareMeterDegreeKelvin"), @Range("cubicFeetPerSecond"), @Range("percentObscurationPerFoot"), @Range("percentObscurationPerMeter"), @Range("milliohms"), @Range("megawattHours"), @Range("kiloBtus"), @Range("megaBtus"), @Range("kilojoulesPerKilogramDryAir"), @Range("megajoulesPerKilogramDryAir"), @Range("kilojoulesPerDegreeKelvin"), @Range("megajoulesPerDegreeKelvin"), @Range("newton"), @Range("gramsPerSecond"), @Range("gramsPerMinute"), @Range("tonsPerHour"), @Range("kiloBtusPerHour"), @Range("hundredthsSeconds"), @Range("milliseconds"), @Range("newtonMeters"), @Range("millimetersPerSecond"), @Range("millimetersPerMinute"), @Range("metersPerMinute"), @Range("metersPerHour"), @Range("cubicMetersPerMinute"), @Range("metersPerSecondPerSecond"), @Range("amperesPerMeter"), @Range("amperesPerSquareMeter"), @Range("ampereSquareMeters"), @Range("farads"), @Range("henrys"), @Range("ohmMeters"), @Range("siemens"), @Range("siemensPerMeter"), @Range("teslas"), @Range("voltsPerDegreeKelvin"), @Range("voltsPerMeter"), @Range("webers"), @Range("candelas"), @Range("candelasPerSquareMeter"), @Range("degreesKelvinPerHour"), @Range("degreesKelvinPerMinute"), @Range("jouleSeconds"), @Range("radiansPerSecond"), @Range("squareMetersPerNewton"), @Range("kilogramsPerCubicMeter"), @Range("newtonSeconds"), @Range("newtonsPerMeter"), @Range("wattsPerMeterPerDegreeKelvin"), @Range("microsiemens"), @Range("cubicFeetPerHour"), @Range("usGallonsPerHour"), @Range("kilometers"), @Range("micrometers"), @Range("grams"), @Range("milligrams"), @Range("milliliters"), @Range("millilitersPerSecond"), @Range("decibels"), @Range("decibelsMillivolt"), @Range("decibelsVolt"), @Range("millisiemens"), @Range("wattHourReactive"), @Range("kilowattHoursReactive"), @Range("megawattHoursReactive"), @Range("millilitersOfWater"), @Range("perMile"), @Range("gramsPerGram"), @Range("kilogramsPerKilogram"), @Range("gramsPerKilogram"), @Range("milligramsPerGram"), @Range("milligramsPerKilogram"), @Range("gramsPerMilliliter"), @Range("gramsPerLiter"), @Range("milligramsPerLiter"), @Range("microgramsPerLiter"), @Range("gramsPerCubicMeter"), @Range("milligramsPerCubicMeter"), @Range("microgramsPerCubicMeter"), @Range("nanogramsPerCubicMeter"), @Range("gramsPerCubicCentimeter"), @Range("becquerels"), @Range("kilobecquerels"), @Range("megabecquerels"), @Range("gray"), @Range("milligray"), @Range("microgray"), @Range("sieverts"), @Range("millisieverts"), @Range("microsieverts"), @Range("microsievertsPerHour"), @Range("decibelsA"), @Range("nephelometricTurbidityUnit"), @Range("ph"), @Range("gramsPerSquareMeter"), @Range("minutesPerDegreeKelvin"), @Range("ohmMeterSquaredPerMeter"), @Range("ampereSeconds"), @Range("voltAmpereHour"), @Range("kilovoltAmpereHour"), @Range("megavoltAmpereHour"), @Range("voltAmpereReactiveHour"), @Range("kilovoltAmpereReactiveHour"), @Range("megavoltAmpereReactiveHour"), @Range("voltSquaredHours"), @Range("ampereSquaredHours"), @Range("joulesPerHour"), @Range("cubicFeetPerDay"), @Range("cubicMetersPerDay"), @Range("wattHourPerCubicMeter"), @Range("joulesPerCubicMeter"), @Range("molesPercent"), @Range("pascalSecond"), @Range("millionStandardCubicFeetPerMinute"), @Range(
      value = "standardCubicFeetPerDay",
      ordinal = 47808
   ), @Range(
      value = "millionStandardCubicFeetPerDay",
      ordinal = 47809
   ), @Range(
      value = "thousandCubicFeetPerDay",
      ordinal = 47810
   ), @Range(
      value = "thousandStandardCubicFeetPerDay",
      ordinal = 47811
   ), @Range(
      value = "poundsMassPerDay",
      ordinal = 47812
   ), @Range(
      value = "millirems",
      ordinal = 47814
   ), @Range(
      value = "milliremsPerHour",
      ordinal = 47815
   )}
)
public final class BBacnetEngineeringUnits extends BFrozenEnum implements BacnetConst {
   public static final int SQUARE_METERS = 0;
   public static final int SQUARE_FEET = 1;
   public static final int MILLIAMPERES = 2;
   public static final int AMPERES = 3;
   public static final int OHMS = 4;
   public static final int VOLTS = 5;
   public static final int KILOVOLTS = 6;
   public static final int MEGAVOLTS = 7;
   public static final int VOLT_AMPERES = 8;
   public static final int KILOVOLT_AMPERES = 9;
   public static final int MEGAVOLT_AMPERES = 10;
   public static final int VOLT_AMPERES_REACTIVE = 11;
   public static final int KILOVOLT_AMPERES_REACTIVE = 12;
   public static final int MEGAVOLT_AMPERES_REACTIVE = 13;
   public static final int DEGREES_PHASE = 14;
   public static final int POWER_FACTOR = 15;
   public static final int JOULES = 16;
   public static final int KILOJOULES = 17;
   public static final int WATT_HOURS = 18;
   public static final int KILOWATT_HOURS = 19;
   public static final int BTUS = 20;
   public static final int THERMS = 21;
   public static final int TON_HOURS = 22;
   public static final int JOULES_PER_KILOGRAM_DRY_AIR = 23;
   public static final int BTUS_PER_POUND_DRY_AIR = 24;
   public static final int CYCLES_PER_HOUR = 25;
   public static final int CYCLES_PER_MINUTE = 26;
   public static final int HERTZ = 27;
   public static final int GRAMS_OF_WATER_PER_KILOGRAM_DRY_AIR = 28;
   public static final int PERCENT_RELATIVE_HUMIDITY = 29;
   public static final int MILLIMETERS = 30;
   public static final int METERS = 31;
   public static final int INCHES = 32;
   public static final int FEET = 33;
   public static final int WATTS_PER_SQUARE_FOOT = 34;
   public static final int WATTS_PER_SQUARE_METER = 35;
   public static final int LUMENS = 36;
   public static final int LUXES = 37;
   public static final int FOOT_CANDLES = 38;
   public static final int KILOGRAMS = 39;
   public static final int POUNDS_MASS = 40;
   public static final int TONS = 41;
   public static final int KILOGRAMS_PER_SECOND = 42;
   public static final int KILOGRAMS_PER_MINUTE = 43;
   public static final int KILOGRAMS_PER_HOUR = 44;
   public static final int POUNDS_MASS_PER_MINUTE = 45;
   public static final int POUNDS_MASS_PER_HOUR = 46;
   public static final int WATTS = 47;
   public static final int KILOWATTS = 48;
   public static final int MEGAWATTS = 49;
   public static final int BTUS_PER_HOUR = 50;
   public static final int HORSEPOWER = 51;
   public static final int TONS_REFRIGERATION = 52;
   public static final int PASCALS = 53;
   public static final int KILOPASCALS = 54;
   public static final int BARS = 55;
   public static final int POUNDS_FORCE_PER_SQUARE_INCH = 56;
   public static final int CENTIMETERS_OF_WATER = 57;
   public static final int INCHES_OF_WATER = 58;
   public static final int MILLIMETERS_OF_MERCURY = 59;
   public static final int CENTIMETERS_OF_MERCURY = 60;
   public static final int INCHES_OF_MERCURY = 61;
   public static final int DEGREES_CELSIUS = 62;
   public static final int DEGREES_KELVIN = 63;
   public static final int DEGREES_FAHRENHEIT = 64;
   public static final int DEGREE_DAYS_CELSIUS = 65;
   public static final int DEGREE_DAYS_FAHRENHEIT = 66;
   public static final int YEARS = 67;
   public static final int MONTHS = 68;
   public static final int WEEKS = 69;
   public static final int DAYS = 70;
   public static final int HOURS = 71;
   public static final int MINUTES = 72;
   public static final int SECONDS = 73;
   public static final int METERS_PER_SECOND = 74;
   public static final int KILOMETERS_PER_HOUR = 75;
   public static final int FEET_PER_SECOND = 76;
   public static final int FEET_PER_MINUTE = 77;
   public static final int MILES_PER_HOUR = 78;
   public static final int CUBIC_FEET = 79;
   public static final int CUBIC_METERS = 80;
   public static final int IMPERIAL_GALLONS = 81;
   public static final int LITERS = 82;
   public static final int US_GALLONS = 83;
   public static final int CUBIC_FEET_PER_MINUTE = 84;
   public static final int CUBIC_METERS_PER_SECOND = 85;
   public static final int IMPERIAL_GALLONS_PER_MINUTE = 86;
   public static final int LITERS_PER_SECOND = 87;
   public static final int LITERS_PER_MINUTE = 88;
   public static final int US_GALLONS_PER_MINUTE = 89;
   public static final int DEGREES_ANGULAR = 90;
   public static final int DEGREES_CELSIUS_PER_HOUR = 91;
   public static final int DEGREES_CELSIUS_PER_MINUTE = 92;
   public static final int DEGREES_FAHRENHEIT_PER_HOUR = 93;
   public static final int DEGREES_FAHRENHEIT_PER_MINUTE = 94;
   public static final int NO_UNITS = 95;
   public static final int PARTS_PER_MILLION = 96;
   public static final int PARTS_PER_BILLION = 97;
   public static final int PERCENT = 98;
   public static final int PERCENT_PER_SECOND = 99;
   public static final int PER_MINUTE = 100;
   public static final int PER_SECOND = 101;
   public static final int PSI_PER_DEGREE_FAHRENHEIT = 102;
   public static final int RADIANS = 103;
   public static final int REVOLUTIONS_PER_MINUTE = 104;
   public static final int CURRENCY_1 = 105;
   public static final int CURRENCY_2 = 106;
   public static final int CURRENCY_3 = 107;
   public static final int CURRENCY_4 = 108;
   public static final int CURRENCY_5 = 109;
   public static final int CURRENCY_6 = 110;
   public static final int CURRENCY_7 = 111;
   public static final int CURRENCY_8 = 112;
   public static final int CURRENCY_9 = 113;
   public static final int CURRENCY_10 = 114;
   public static final int SQUARE_INCHES = 115;
   public static final int SQUARE_CENTIMETERS = 116;
   public static final int BTUS_PER_POUND = 117;
   public static final int CENTIMETERS = 118;
   public static final int POUNDS_MASS_PER_SECOND = 119;
   public static final int DELTA_DEGREES_FAHRENHEIT = 120;
   public static final int DELTA_DEGREES_KELVIN = 121;
   public static final int KILOHMS = 122;
   public static final int MEGOHMS = 123;
   public static final int MILLIVOLTS = 124;
   public static final int KILOJOULES_PER_KILOGRAM = 125;
   public static final int MEGAJOULES = 126;
   public static final int JOULES_PER_DEGREE_KELVIN = 127;
   public static final int JOULES_PER_KILOGRAM_DEGREE_KELVIN = 128;
   public static final int KILOHERTZ = 129;
   public static final int MEGAHERTZ = 130;
   public static final int PER_HOUR = 131;
   public static final int MILLIWATTS = 132;
   public static final int HECTOPASCALS = 133;
   public static final int MILLIBARS = 134;
   public static final int CUBIC_METERS_PER_HOUR = 135;
   public static final int LITERS_PER_HOUR = 136;
   public static final int KILOWATT_HOURS_PER_SQUARE_METER = 137;
   public static final int KILOWATT_HOURS_PER_SQUARE_FOOT = 138;
   public static final int MEGAJOULES_PER_SQUARE_METER = 139;
   public static final int MEGAJOULES_PER_SQUARE_FOOT = 140;
   public static final int WATTS_PER_SQUARE_METER_DEGREE_KELVIN = 141;
   public static final int CUBIC_FEET_PER_SECOND = 142;
   public static final int PERCENT_OBSCURATION_PER_FOOT = 143;
   public static final int PERCENT_OBSCURATION_PER_METER = 144;
   public static final int MILLIOHMS = 145;
   public static final int MEGAWATT_HOURS = 146;
   public static final int KILO_BTUS = 147;
   public static final int MEGA_BTUS = 148;
   public static final int KILOJOULES_PER_KILOGRAM_DRY_AIR = 149;
   public static final int MEGAJOULES_PER_KILOGRAM_DRY_AIR = 150;
   public static final int KILOJOULES_PER_DEGREE_KELVIN = 151;
   public static final int MEGAJOULES_PER_DEGREE_KELVIN = 152;
   public static final int NEWTON = 153;
   public static final int GRAMS_PER_SECOND = 154;
   public static final int GRAMS_PER_MINUTE = 155;
   public static final int TONS_PER_HOUR = 156;
   public static final int KILO_BTUS_PER_HOUR = 157;
   public static final int HUNDREDTHS_SECONDS = 158;
   public static final int MILLISECONDS = 159;
   public static final int NEWTON_METERS = 160;
   public static final int MILLIMETERS_PER_SECOND = 161;
   public static final int MILLIMETERS_PER_MINUTE = 162;
   public static final int METERS_PER_MINUTE = 163;
   public static final int METERS_PER_HOUR = 164;
   public static final int CUBIC_METERS_PER_MINUTE = 165;
   public static final int METERS_PER_SECOND_PER_SECOND = 166;
   public static final int AMPERES_PER_METER = 167;
   public static final int AMPERES_PER_SQUARE_METER = 168;
   public static final int AMPERE_SQUARE_METERS = 169;
   public static final int FARADS = 170;
   public static final int HENRYS = 171;
   public static final int OHM_METERS = 172;
   public static final int SIEMENS = 173;
   public static final int SIEMENS_PER_METER = 174;
   public static final int TESLAS = 175;
   public static final int VOLTS_PER_DEGREE_KELVIN = 176;
   public static final int VOLTS_PER_METER = 177;
   public static final int WEBERS = 178;
   public static final int CANDELAS = 179;
   public static final int CANDELAS_PER_SQUARE_METER = 180;
   public static final int DEGREES_KELVIN_PER_HOUR = 181;
   public static final int DEGREES_KELVIN_PER_MINUTE = 182;
   public static final int JOULE_SECONDS = 183;
   public static final int RADIANS_PER_SECOND = 184;
   public static final int SQUARE_METERS_PER_NEWTON = 185;
   public static final int KILOGRAMS_PER_CUBIC_METER = 186;
   public static final int NEWTON_SECONDS = 187;
   public static final int NEWTONS_PER_METER = 188;
   public static final int WATTS_PER_METER_PER_DEGREE_KELVIN = 189;
   public static final int MICROSIEMENS = 190;
   public static final int CUBIC_FEET_PER_HOUR = 191;
   public static final int US_GALLONS_PER_HOUR = 192;
   public static final int KILOMETERS = 193;
   public static final int MICROMETERS = 194;
   public static final int GRAMS = 195;
   public static final int MILLIGRAMS = 196;
   public static final int MILLILITERS = 197;
   public static final int MILLILITERS_PER_SECOND = 198;
   public static final int DECIBELS = 199;
   public static final int DECIBELS_MILLIVOLT = 200;
   public static final int DECIBELS_VOLT = 201;
   public static final int MILLISIEMENS = 202;
   public static final int WATT_HOUR_REACTIVE = 203;
   public static final int KILOWATT_HOURS_REACTIVE = 204;
   public static final int MEGAWATT_HOURS_REACTIVE = 205;
   public static final int MILLILITERS_OF_WATER = 206;
   public static final int PER_MILE = 207;
   public static final int GRAMS_PER_GRAM = 208;
   public static final int KILOGRAMS_PER_KILOGRAM = 209;
   public static final int GRAMS_PER_KILOGRAM = 210;
   public static final int MILLIGRAMS_PER_GRAM = 211;
   public static final int MILLIGRAMS_PER_KILOGRAM = 212;
   public static final int GRAMS_PER_MILLILITER = 213;
   public static final int GRAMS_PER_LITER = 214;
   public static final int MILLIGRAMS_PER_LITER = 215;
   public static final int MICROGRAMS_PER_LITER = 216;
   public static final int GRAMS_PER_CUBIC_METER = 217;
   public static final int MILLIGRAMS_PER_CUBIC_METER = 218;
   public static final int MICROGRAMS_PER_CUBIC_METER = 219;
   public static final int NANOGRAMS_PER_CUBIC_METER = 220;
   public static final int GRAMS_PER_CUBIC_CENTIMETER = 221;
   public static final int BECQUERELS = 222;
   public static final int KILOBECQUERELS = 223;
   public static final int MEGABECQUERELS = 224;
   public static final int GRAY = 225;
   public static final int MILLIGRAY = 226;
   public static final int MICROGRAY = 227;
   public static final int SIEVERTS = 228;
   public static final int MILLISIEVERTS = 229;
   public static final int MICROSIEVERTS = 230;
   public static final int MICROSIEVERTS_PER_HOUR = 231;
   public static final int DECIBELS_A = 232;
   public static final int NEPHELOMETRIC_TURBIDITY_UNIT = 233;
   public static final int PH = 234;
   public static final int GRAMS_PER_SQUARE_METER = 235;
   public static final int MINUTES_PER_DEGREE_KELVIN = 236;
   public static final int OHM_METER_SQUARED_PER_METER = 237;
   public static final int AMPERE_SECONDS = 238;
   public static final int VOLT_AMPERE_HOUR = 239;
   public static final int KILOVOLT_AMPERE_HOUR = 240;
   public static final int MEGAVOLT_AMPERE_HOUR = 241;
   public static final int VOLT_AMPERE_REACTIVE_HOUR = 242;
   public static final int KILOVOLT_AMPERE_REACTIVE_HOUR = 243;
   public static final int MEGAVOLT_AMPERE_REACTIVE_HOUR = 244;
   public static final int VOLT_SQUARED_HOURS = 245;
   public static final int AMPERE_SQUARED_HOURS = 246;
   public static final int JOULES_PER_HOUR = 247;
   public static final int CUBIC_FEET_PER_DAY = 248;
   public static final int CUBIC_METERS_PER_DAY = 249;
   public static final int WATT_HOUR_PER_CUBIC_METER = 250;
   public static final int JOULES_PER_CUBIC_METER = 251;
   public static final int MOLES_PERCENT = 252;
   public static final int PASCAL_SECOND = 253;
   public static final int MILLION_STANDARD_CUBIC_FEET_PER_MINUTE = 254;
   public static final int STANDARD_CUBIC_FEET_PER_DAY = 47808;
   public static final int MILLION_STANDARD_CUBIC_FEET_PER_DAY = 47809;
   public static final int THOUSAND_CUBIC_FEET_PER_DAY = 47810;
   public static final int THOUSAND_STANDARD_CUBIC_FEET_PER_DAY = 47811;
   public static final int POUNDS_MASS_PER_DAY = 47812;
   public static final int MILLIREMS = 47814;
   public static final int MILLIREMS_PER_HOUR = 47815;
   public static final String SQUARE_METERS_NAME = "square meter";
   public static final String SQUARE_FEET_NAME = "square foot";
   public static final String MILLIAMPERES_NAME = "milliampere";
   public static final String AMPERES_NAME = "ampere";
   public static final String OHMS_NAME = "ohm";
   public static final String VOLTS_NAME = "volt";
   public static final String KILOVOLTS_NAME = "kilovolt";
   public static final String MEGAVOLTS_NAME = "megavolt";
   public static final String VOLT_AMPERES_NAME = "volt ampere";
   public static final String KILOVOLT_AMPERES_NAME = "kilovolt ampere";
   public static final String MEGAVOLT_AMPERES_NAME = "megavolt ampere";
   public static final String VOLT_AMPERES_REACTIVE_NAME = "volt ampere reactive";
   public static final String KILOVOLT_AMPERES_REACTIVE_NAME = "kilovolt ampere reactive";
   public static final String MEGAVOLT_AMPERES_REACTIVE_NAME = "megavolt ampere reactive";
   public static final String DEGREES_PHASE_NAME = "degrees phase";
   public static final String POWER_FACTOR_NAME = "power factor";
   public static final String JOULES_NAME = "joule";
   public static final String KILOJOULES_NAME = "kilojoule";
   public static final String WATT_HOURS_NAME = "watt hour";
   public static final String KILOWATT_HOURS_NAME = "kilowatt hour";
   public static final String BTUS_NAME = "btu";
   public static final String THERMS_NAME = "therm";
   public static final String TON_HOURS_NAME = "tons refrigeration hour";
   public static final String JOULES_PER_KILOGRAM_DRY_AIR_NAME = "joules per kilogram dry air";
   public static final String BTUS_PER_POUND_DRY_AIR_NAME = "btus per pound dry air";
   public static final String CYCLES_PER_HOUR_NAME = "cycles per hour";
   public static final String CYCLES_PER_MINUTE_NAME = "cycles per minute";
   public static final String HERTZ_NAME = "hertz";
   public static final String GRAMS_OF_WATER_PER_KILOGRAM_DRY_AIR_NAME = "grams of water per kilogram dry air";
   public static final String PERCENT_RELATIVE_HUMIDITY_NAME = "percent relative humidity";
   public static final String MILLIMETERS_NAME = "millimeter";
   public static final String METERS_NAME = "meter";
   public static final String INCHES_NAME = "inch";
   public static final String FEET_NAME = "foot";
   public static final String WATTS_PER_SQUARE_FOOT_NAME = "watts per square foot";
   public static final String WATTS_PER_SQUARE_METER_NAME = "watts per square meter";
   public static final String LUMENS_NAME = "lumen";
   public static final String LUXES_NAME = "lux";
   public static final String FOOT_CANDLES_NAME = "footcandle";
   public static final String KILOGRAMS_NAME = "kilogram";
   public static final String POUNDS_MASS_NAME = "pound";
   public static final String TONS_NAME = "metric ton";
   public static final String KILOGRAMS_PER_SECOND_NAME = "kilograms per second";
   public static final String KILOGRAMS_PER_MINUTE_NAME = "kilograms per minute";
   public static final String KILOGRAMS_PER_HOUR_NAME = "kilograms per hour";
   public static final String POUNDS_MASS_PER_MINUTE_NAME = "pounds per minute";
   public static final String POUNDS_MASS_PER_HOUR_NAME = "pounds per hour";
   public static final String WATTS_NAME = "watt";
   public static final String KILOWATTS_NAME = "kilowatt";
   public static final String MEGAWATTS_NAME = "megawatt";
   public static final String BTUS_PER_HOUR_NAME = "btus per hour";
   public static final String HORSEPOWER_NAME = "horsepower";
   public static final String TONS_REFRIGERATION_NAME = "tons refrigeration";
   public static final String PASCALS_NAME = "pascal";
   public static final String KILOPASCALS_NAME = "kilopascal";
   public static final String BARS_NAME = "bar";
   public static final String POUNDS_FORCE_PER_SQUARE_INCH_NAME = "pounds per square inch";
   public static final String CENTIMETERS_OF_WATER_NAME = "centimeters of water";
   public static final String INCHES_OF_WATER_NAME = "inches of water";
   public static final String MILLIMETERS_OF_MERCURY_NAME = "millimeters of mercury";
   public static final String CENTIMETERS_OF_MERCURY_NAME = "centimeters of mercury";
   public static final String INCHES_OF_MERCURY_NAME = "inches of mercury";
   public static final String DEGREES_CELSIUS_NAME = "celsius";
   public static final String DEGREES_KELVIN_NAME = "kelvin";
   public static final String DEGREES_FAHRENHEIT_NAME = "fahrenheit";
   public static final String DEGREE_DAYS_CELSIUS_NAME = "degree days celsius";
   public static final String DEGREE_DAYS_FAHRENHEIT_NAME = "degree days fahrenheit";
   public static final String YEARS_NAME = "year";
   public static final String MONTHS_NAME = "julian month";
   public static final String WEEKS_NAME = "week";
   public static final String DAYS_NAME = "day";
   public static final String HOURS_NAME = "hour";
   public static final String MINUTES_NAME = "minute";
   public static final String SECONDS_NAME = "second";
   public static final String METERS_PER_SECOND_NAME = "meters per second";
   public static final String KILOMETERS_PER_HOUR_NAME = "kilometers per hour";
   public static final String FEET_PER_SECOND_NAME = "feet per second";
   public static final String FEET_PER_MINUTE_NAME = "feet per minute";
   public static final String MILES_PER_HOUR_NAME = "miles per hour";
   public static final String CUBIC_FEET_NAME = "cubic foot";
   public static final String CUBIC_METERS_NAME = "cubic meter";
   public static final String IMPERIAL_GALLONS_NAME = "imperial gallon";
   public static final String LITERS_NAME = "liter";
   public static final String US_GALLONS_NAME = "gallon";
   public static final String CUBIC_FEET_PER_MINUTE_NAME = "cubic feet per minute";
   public static final String CUBIC_METERS_PER_SECOND_NAME = "cubic meters per second";
   public static final String IMPERIAL_GALLONS_PER_MINUTE_NAME = "imperial gallons per minute";
   public static final String LITERS_PER_SECOND_NAME = "liters per second";
   public static final String LITERS_PER_MINUTE_NAME = "liters per minute";
   public static final String US_GALLONS_PER_MINUTE_NAME = "gallons per minute";
   public static final String DEGREES_ANGULAR_NAME = "degrees angular";
   public static final String DEGREES_CELSIUS_PER_HOUR_NAME = "degrees celsius per hour";
   public static final String DEGREES_CELSIUS_PER_MINUTE_NAME = "degrees celsius per minute";
   public static final String DEGREES_FAHRENHEIT_PER_HOUR_NAME = "degrees fahrenheit per hour";
   public static final String DEGREES_FAHRENHEIT_PER_MINUTE_NAME = "degrees fahrenheit per minute";
   public static final String NO_UNITS_NAME = "null";
   public static final String PARTS_PER_MILLION_NAME = "parts per million";
   public static final String PARTS_PER_BILLION_NAME = "parts per billion";
   public static final String PERCENT_NAME = "percent";
   public static final String PERCENT_PER_SECOND_NAME = "percent per second";
   public static final String PER_MINUTE_NAME = "per minute";
   public static final String PER_SECOND_NAME = "per second";
   public static final String PSI_PER_DEGREE_FAHRENHEIT_NAME = "psi per degree fahrenheit";
   public static final String RADIANS_NAME = "radian";
   public static final String REVOLUTIONS_PER_MINUTE_NAME = "revolutions per minute";
   public static final String CURRENCY_1_NAME = "currency1";
   public static final String CURRENCY_2_NAME = "currency2";
   public static final String CURRENCY_3_NAME = "currency3";
   public static final String CURRENCY_4_NAME = "currency4";
   public static final String CURRENCY_5_NAME = "currency5";
   public static final String CURRENCY_6_NAME = "currency6";
   public static final String CURRENCY_7_NAME = "currency7";
   public static final String CURRENCY_8_NAME = "currency8";
   public static final String CURRENCY_9_NAME = "currency9";
   public static final String CURRENCY_10_NAME = "currency10";
   public static final String SQUARE_INCHES_NAME = "square inch";
   public static final String SQUARE_CENTIMETERS_NAME = "square centimeter";
   public static final String BTUS_PER_POUND_NAME = "btus per pound";
   public static final String CENTIMETERS_NAME = "centimeter";
   public static final String POUNDS_MASS_PER_SECOND_NAME = "pounds per second";
   public static final String DELTA_DEGREES_FAHRENHEIT_NAME = "fahrenheit degrees";
   public static final String DELTA_DEGREES_KELVIN_NAME = "kelvin degrees";
   public static final String KILOHMS_NAME = "kilohm";
   public static final String MEGOHMS_NAME = "megohm";
   public static final String MILLIVOLTS_NAME = "millivolt";
   public static final String KILOJOULES_PER_KILOGRAM_NAME = "kilojoules per kilogram";
   public static final String MEGAJOULES_NAME = "megajoule";
   public static final String JOULES_PER_DEGREE_KELVIN_NAME = "joules per degree kelvin";
   public static final String JOULES_PER_KILOGRAM_DEGREE_KELVIN_NAME = "joules per kilogram degree kelvin";
   public static final String KILOHERTZ_NAME = "kilohertz";
   public static final String MEGAHERTZ_NAME = "megahertz";
   public static final String PER_HOUR_NAME = "per hour";
   public static final String MILLIWATTS_NAME = "milliwatt";
   public static final String HECTOPASCALS_NAME = "hectopascal";
   public static final String MILLIBARS_NAME = "millibar";
   public static final String CUBIC_METERS_PER_HOUR_NAME = "cubic meters per hour";
   public static final String LITERS_PER_HOUR_NAME = "liters per hour";
   public static final String KILOWATT_HOURS_PER_SQUARE_METER_NAME = "kilowatt hours per square meter";
   public static final String KILOWATT_HOURS_PER_SQUARE_FOOT_NAME = "kilowatt hours per square foot";
   public static final String MEGAJOULES_PER_SQUARE_METER_NAME = "megajoules per square meter";
   public static final String MEGAJOULES_PER_SQUARE_FOOT_NAME = "megajoules per square foot";
   public static final String WATTS_PER_SQUARE_METER_DEGREE_KELVIN_NAME = "watts per square meter degree kelvin";
   public static final String CUBIC_FEET_PER_SECOND_NAME = "cubic feet per second";
   public static final String PERCENT_OBSCURATION_PER_FOOT_NAME = "percent obscuration per foot";
   public static final String PERCENT_OBSCURATION_PER_METER_NAME = "percent obscuration per meter";
   public static final String MILLIOHMS_NAME = "milliohm";
   public static final String MEGAWATT_HOURS_NAME = "megawatt hour";
   public static final String KILO_BTUS_NAME = "kilobtu";
   public static final String MEGA_BTUS_NAME = "megabtu";
   public static final String KILOJOULES_PER_KILOGRAM_DRY_AIR_NAME = "kilojoules per kilogram dry air";
   public static final String MEGAJOULES_PER_KILOGRAM_DRY_AIR_NAME = "megajoules per kilogram dry air";
   public static final String KILOJOULES_PER_DEGREE_KELVIN_NAME = "kilojoules per degree kelvin";
   public static final String MEGAJOULES_PER_DEGREE_KELVIN_NAME = "megajoules per degree kelvin";
   public static final String NEWTON_NAME = "newton";
   public static final String GRAMS_PER_SECOND_NAME = "grams per second";
   public static final String GRAMS_PER_MINUTE_NAME = "grams per minute";
   public static final String TONS_PER_HOUR_NAME = "metric tons per hour";
   public static final String KILO_BTUS_PER_HOUR_NAME = "kilobtus per hour";
   public static final String HUNDREDTHS_SECONDS_NAME = "hundredths second";
   public static final String MILLISECONDS_NAME = "millisecond";
   public static final String NEWTON_METERS_NAME = "newton meter";
   public static final String MILLIMETERS_PER_SECOND_NAME = "millimeters per second";
   public static final String MILLIMETERS_PER_MINUTE_NAME = "millimeters per minute";
   public static final String METERS_PER_MINUTE_NAME = "meters per minute";
   public static final String METERS_PER_HOUR_NAME = "meters per hour";
   public static final String CUBIC_METERS_PER_MINUTE_NAME = "cubic meters per minute";
   public static final String METERS_PER_SECOND_PER_SECOND_NAME = "meters per second squared";
   public static final String AMPERES_PER_METER_NAME = "amperes per meter";
   public static final String AMPERES_PER_SQUARE_METER_NAME = "amperes per square meter";
   public static final String AMPERE_SQUARE_METERS_NAME = "ampere square meter";
   public static final String FARADS_NAME = "farad";
   public static final String HENRYS_NAME = "henry";
   public static final String OHM_METERS_NAME = "ohm meter";
   public static final String SIEMENS_NAME = "siemens";
   public static final String SIEMENS_PER_METER_NAME = "siemens per meter";
   public static final String TESLAS_NAME = "tesla";
   public static final String VOLTS_PER_DEGREE_KELVIN_NAME = "volts per degree kelvin";
   public static final String VOLTS_PER_METER_NAME = "volts per meter";
   public static final String WEBERS_NAME = "weber";
   public static final String CANDELAS_NAME = "candela";
   public static final String CANDELAS_PER_SQUARE_METER_NAME = "candelas per square meter";
   public static final String DEGREES_KELVIN_PER_HOUR_NAME = "degrees kelvin per hour";
   public static final String DEGREES_KELVIN_PER_MINUTE_NAME = "degrees kelvin per minute";
   public static final String JOULE_SECONDS_NAME = "joule second";
   public static final String RADIANS_PER_SECOND_NAME = "radians per second";
   public static final String SQUARE_METERS_PER_NEWTON_NAME = "square meters per newton";
   public static final String KILOGRAMS_PER_CUBIC_METER_NAME = "kilograms per cubic meter";
   public static final String NEWTON_SECONDS_NAME = "newton second";
   public static final String NEWTONS_PER_METER_NAME = "newtons per meter";
   public static final String WATTS_PER_METER_PER_DEGREE_KELVIN_NAME = "watts per meter degree kelvin";
   public static final String MICROSIEMENS_NAME = "microsiemens";
   public static final String CUBIC_FEET_PER_HOUR_NAME = "cubic feet per hour";
   public static final String US_GALLONS_PER_HOUR_NAME = "gallons per hour";
   public static final String KILOMETERS_NAME = "kilometer";
   public static final String MICROMETERS_NAME = "micrometer";
   public static final String GRAMS_NAME = "gram";
   public static final String MILLIGRAMS_NAME = "milligram";
   public static final String MILLILITERS_NAME = "milliliter";
   public static final String MILLILITERS_PER_SECOND_NAME = "milliliters per second";
   public static final String DECIBELS_NAME = "decibel";
   public static final String DECIBELS_MILLIVOLT_NAME = "db milliVolt";
   public static final String DECIBELS_VOLT_NAME = "db volt";
   public static final String MILLISIEMENS_NAME = "millisiemens";
   public static final String WATT_HOUR_REACTIVE_NAME = "watt reactive hour";
   public static final String KILOWATT_HOURS_REACTIVE_NAME = "kilowatt reactive hour";
   public static final String MEGAWATT_HOURS_REACTIVE_NAME = "megawatt reactive hour";
   public static final String MILLILITERS_OF_WATER_NAME = "milliliters of water";
   public static final String PER_MILE_NAME = "per mile";
   public static final String GRAMS_PER_GRAM_NAME = "grams per gram";
   public static final String KILOGRAMS_PER_KILOGRAM_NAME = "kilograms per kilogram";
   public static final String GRAMS_PER_KILOGRAM_NAME = "grams per kilogram";
   public static final String MILLIGRAMS_PER_GRAM_NAME = "milligrams per gram";
   public static final String MILLIGRAMS_PER_KILOGRAM_NAME = "milligrams per kilogram";
   public static final String GRAMS_PER_MILLILITER_NAME = "grams per milliliter";
   public static final String GRAMS_PER_LITER_NAME = "grams per liter";
   public static final String MILLIGRAMS_PER_LITER_NAME = "milligrams per liter";
   public static final String MICROGRAMS_PER_LITER_NAME = "micrograms per liter";
   public static final String GRAMS_PER_CUBIC_METER_NAME = "grams per cubic meter";
   public static final String MILLIGRAMS_PER_CUBIC_METER_NAME = "milligrams per cubic meter";
   public static final String MICROGRAMS_PER_CUBIC_METER_NAME = "micrograms per cubic meter";
   public static final String NANOGRAMS_PER_CUBIC_METER_NAME = "nanograms per cubic meter";
   public static final String GRAMS_PER_CUBIC_CENTIMETER_NAME = "grams per cubic centimeter";
   public static final String BECQUERELS_NAME = "becquerel";
   public static final String KILOBECQUERELS_NAME = "kilobecquerel";
   public static final String MEGABECQUERELS_NAME = "megabecquerel";
   public static final String GRAY_NAME = "gray";
   public static final String MILLIGRAY_NAME = "milligray";
   public static final String MICROGRAY_NAME = "microgray";
   public static final String SIEVERTS_NAME = "sievert";
   public static final String MILLISIEVERTS_NAME = "millisievert";
   public static final String MICROSIEVERTS_NAME = "microsievert";
   public static final String MICROSIEVERTS_PER_HOUR_NAME = "microsievert per hour";
   public static final String DECIBELS_A_NAME = "db ampere";
   public static final String NEPHELOMETRIC_TURBIDITY_UNIT_NAME = "nephelometric turbidity units";
   public static final String PH_NAME = "pH";
   public static final String GRAMS_PER_SQUARE_METER_NAME = "grams per square meter";
   public static final String MINUTES_PER_DEGREE_KELVIN_NAME = "minutes per degree kelvin";
   public static final String OHM_METER_SQUARED_PER_METER_NAME = "ohm meter squared per meter";
   public static final String AMPERE_SECONDS_NAME = "ampere seconds";
   public static final String VOLT_AMPERE_HOUR_NAME = "volt ampere hour";
   public static final String KILOVOLT_AMPERE_HOUR_NAME = "kilovolt ampere hour";
   public static final String MEGAVOLT_AMPERE_HOUR_NAME = "megavolt ampere hour";
   public static final String VOLT_AMPERE_REACTIVE_HOUR_NAME = "volt ampere reactive hour";
   public static final String KILOVOLT_AMPERE_REACTIVE_HOUR_NAME = "kilovolt ampere reactive hour";
   public static final String MEGAVOLT_AMPERE_REACTIVE_HOUR_NAME = "megavolt ampere reactive hour";
   public static final String VOLT_SQUARED_HOURS_NAME = "volt squared hours";
   public static final String AMPERE_SQUARED_HOURS_NAME = "ampere squared hours";
   public static final String JOULES_PER_HOUR_NAME = "joules per hour";
   public static final String CUBIC_FEET_PER_DAY_NAME = "cubic feet per day";
   public static final String CUBIC_METERS_PER_DAY_NAME = "cubic meters per day";
   public static final String WATT_HOUR_PER_CUBIC_METER_NAME = "watt hour per cubic meter";
   public static final String JOULES_PER_CUBIC_METER_NAME = "joules per cubic meter";
   public static final String MOLES_PERCENT_NAME = "moles percent";
   public static final String PASCAL_SECOND_NAME = "pascal second";
   public static final String MILLION_STANDARD_CUBIC_FEET_PER_MINUTE_NAME = "million standard cubic feet per minute";
   public static final String STANDARD_CUBIC_FEET_PER_DAY_NAME = "standard cubic feet per day";
   public static final String MILLION_STANDARD_CUBIC_FEET_PER_DAY_NAME = "million standard cubic feet per day";
   public static final String THOUSAND_CUBIC_FEET_PER_DAY_NAME = "thousand cubic feet per day";
   public static final String THOUSAND_STANDARD_CUBIC_FEET_PER_DAY_NAME = "thousand standard cubic feet per day";
   public static final String POUNDS_MASS_PER_DAY_NAME = "pounds mass per day";
   public static final String MILLIREMS_NAME = "millirems";
   public static final String MILLIREMS_PER_HOUR_NAME = "millirems per hour";
   public static final BBacnetEngineeringUnits squareMeters = new BBacnetEngineeringUnits(0, "square meter");
   public static final BBacnetEngineeringUnits squareFeet = new BBacnetEngineeringUnits(1, "square foot");
   public static final BBacnetEngineeringUnits milliamperes = new BBacnetEngineeringUnits(2, "milliampere");
   public static final BBacnetEngineeringUnits amperes = new BBacnetEngineeringUnits(3, "ampere");
   public static final BBacnetEngineeringUnits ohms = new BBacnetEngineeringUnits(4, "ohm");
   public static final BBacnetEngineeringUnits volts = new BBacnetEngineeringUnits(5, "volt");
   public static final BBacnetEngineeringUnits kilovolts = new BBacnetEngineeringUnits(6, "kilovolt");
   public static final BBacnetEngineeringUnits megavolts = new BBacnetEngineeringUnits(7, "megavolt");
   public static final BBacnetEngineeringUnits voltAmperes = new BBacnetEngineeringUnits(8, "volt ampere");
   public static final BBacnetEngineeringUnits kilovoltAmperes = new BBacnetEngineeringUnits(9, "kilovolt ampere");
   public static final BBacnetEngineeringUnits megavoltAmperes = new BBacnetEngineeringUnits(10, "megavolt ampere");
   public static final BBacnetEngineeringUnits voltAmperesReactive = new BBacnetEngineeringUnits(11, "volt ampere reactive");
   public static final BBacnetEngineeringUnits kilovoltAmperesReactive = new BBacnetEngineeringUnits(12, "kilovolt ampere reactive");
   public static final BBacnetEngineeringUnits megavoltAmperesReactive = new BBacnetEngineeringUnits(13, "megavolt ampere reactive");
   public static final BBacnetEngineeringUnits degreesPhase = new BBacnetEngineeringUnits(14, "degrees phase");
   public static final BBacnetEngineeringUnits powerFactor = new BBacnetEngineeringUnits(15, "power factor");
   public static final BBacnetEngineeringUnits joules = new BBacnetEngineeringUnits(16, "joule");
   public static final BBacnetEngineeringUnits kilojoules = new BBacnetEngineeringUnits(17, "kilojoule");
   public static final BBacnetEngineeringUnits wattHours = new BBacnetEngineeringUnits(18, "watt hour");
   public static final BBacnetEngineeringUnits kilowattHours = new BBacnetEngineeringUnits(19, "kilowatt hour");
   public static final BBacnetEngineeringUnits btus = new BBacnetEngineeringUnits(20, "btu");
   public static final BBacnetEngineeringUnits therms = new BBacnetEngineeringUnits(21, "therm");
   public static final BBacnetEngineeringUnits tonHours = new BBacnetEngineeringUnits(22, "tons refrigeration hour");
   public static final BBacnetEngineeringUnits joulesPerKilogramDryAir = new BBacnetEngineeringUnits(23, "joules per kilogram dry air");
   public static final BBacnetEngineeringUnits btusPerPoundDryAir = new BBacnetEngineeringUnits(24, "btus per pound dry air");
   public static final BBacnetEngineeringUnits cyclesPerHour = new BBacnetEngineeringUnits(25, "cycles per hour");
   public static final BBacnetEngineeringUnits cyclesPerMinute = new BBacnetEngineeringUnits(26, "cycles per minute");
   public static final BBacnetEngineeringUnits hertz = new BBacnetEngineeringUnits(27, "hertz");
   public static final BBacnetEngineeringUnits gramsOfWaterPerKilogramDryAir = new BBacnetEngineeringUnits(28, "grams of water per kilogram dry air");
   public static final BBacnetEngineeringUnits percentRelativeHumidity = new BBacnetEngineeringUnits(29, "percent relative humidity");
   public static final BBacnetEngineeringUnits millimeters = new BBacnetEngineeringUnits(30, "millimeter");
   public static final BBacnetEngineeringUnits meters = new BBacnetEngineeringUnits(31, "meter");
   public static final BBacnetEngineeringUnits inches = new BBacnetEngineeringUnits(32, "inch");
   public static final BBacnetEngineeringUnits feet = new BBacnetEngineeringUnits(33, "foot");
   public static final BBacnetEngineeringUnits wattsPerSquareFoot = new BBacnetEngineeringUnits(34, "watts per square foot");
   public static final BBacnetEngineeringUnits wattsPerSquareMeter = new BBacnetEngineeringUnits(35, "watts per square meter");
   public static final BBacnetEngineeringUnits lumens = new BBacnetEngineeringUnits(36, "lumen");
   public static final BBacnetEngineeringUnits luxes = new BBacnetEngineeringUnits(37, "lux");
   public static final BBacnetEngineeringUnits footCandles = new BBacnetEngineeringUnits(38, "footcandle");
   public static final BBacnetEngineeringUnits kilograms = new BBacnetEngineeringUnits(39, "kilogram");
   public static final BBacnetEngineeringUnits poundsMass = new BBacnetEngineeringUnits(40, "pound");
   public static final BBacnetEngineeringUnits tons = new BBacnetEngineeringUnits(41, "metric ton");
   public static final BBacnetEngineeringUnits kilogramsPerSecond = new BBacnetEngineeringUnits(42, "kilograms per second");
   public static final BBacnetEngineeringUnits kilogramsPerMinute = new BBacnetEngineeringUnits(43, "kilograms per minute");
   public static final BBacnetEngineeringUnits kilogramsPerHour = new BBacnetEngineeringUnits(44, "kilograms per hour");
   public static final BBacnetEngineeringUnits poundsMassPerMinute = new BBacnetEngineeringUnits(45, "pounds per minute");
   public static final BBacnetEngineeringUnits poundsMassPerHour = new BBacnetEngineeringUnits(46, "pounds per hour");
   public static final BBacnetEngineeringUnits watts = new BBacnetEngineeringUnits(47, "watt");
   public static final BBacnetEngineeringUnits kilowatts = new BBacnetEngineeringUnits(48, "kilowatt");
   public static final BBacnetEngineeringUnits megawatts = new BBacnetEngineeringUnits(49, "megawatt");
   public static final BBacnetEngineeringUnits btusPerHour = new BBacnetEngineeringUnits(50, "btus per hour");
   public static final BBacnetEngineeringUnits horsepower = new BBacnetEngineeringUnits(51, "horsepower");
   public static final BBacnetEngineeringUnits tonsRefrigeration = new BBacnetEngineeringUnits(52, "tons refrigeration");
   public static final BBacnetEngineeringUnits pascals = new BBacnetEngineeringUnits(53, "pascal");
   public static final BBacnetEngineeringUnits kilopascals = new BBacnetEngineeringUnits(54, "kilopascal");
   public static final BBacnetEngineeringUnits bars = new BBacnetEngineeringUnits(55, "bar");
   public static final BBacnetEngineeringUnits poundsForcePerSquareInch = new BBacnetEngineeringUnits(56, "pounds per square inch");
   public static final BBacnetEngineeringUnits centimetersOfWater = new BBacnetEngineeringUnits(57, "centimeters of water");
   public static final BBacnetEngineeringUnits inchesOfWater = new BBacnetEngineeringUnits(58, "inches of water");
   public static final BBacnetEngineeringUnits millimetersOfMercury = new BBacnetEngineeringUnits(59, "millimeters of mercury");
   public static final BBacnetEngineeringUnits centimetersOfMercury = new BBacnetEngineeringUnits(60, "centimeters of mercury");
   public static final BBacnetEngineeringUnits inchesOfMercury = new BBacnetEngineeringUnits(61, "inches of mercury");
   public static final BBacnetEngineeringUnits degreesCelsius = new BBacnetEngineeringUnits(62, "celsius");
   public static final BBacnetEngineeringUnits degreesKelvin = new BBacnetEngineeringUnits(63, "kelvin");
   public static final BBacnetEngineeringUnits degreesFahrenheit = new BBacnetEngineeringUnits(64, "fahrenheit");
   public static final BBacnetEngineeringUnits degreeDaysCelsius = new BBacnetEngineeringUnits(65, "degree days celsius");
   public static final BBacnetEngineeringUnits degreeDaysFahrenheit = new BBacnetEngineeringUnits(66, "degree days fahrenheit");
   public static final BBacnetEngineeringUnits years = new BBacnetEngineeringUnits(67, "year");
   public static final BBacnetEngineeringUnits months = new BBacnetEngineeringUnits(68, "julian month");
   public static final BBacnetEngineeringUnits weeks = new BBacnetEngineeringUnits(69, "week");
   public static final BBacnetEngineeringUnits days = new BBacnetEngineeringUnits(70, "day");
   public static final BBacnetEngineeringUnits hours = new BBacnetEngineeringUnits(71, "hour");
   public static final BBacnetEngineeringUnits minutes = new BBacnetEngineeringUnits(72, "minute");
   public static final BBacnetEngineeringUnits seconds = new BBacnetEngineeringUnits(73, "second");
   public static final BBacnetEngineeringUnits metersPerSecond = new BBacnetEngineeringUnits(74, "meters per second");
   public static final BBacnetEngineeringUnits kilometersPerHour = new BBacnetEngineeringUnits(75, "kilometers per hour");
   public static final BBacnetEngineeringUnits feetPerSecond = new BBacnetEngineeringUnits(76, "feet per second");
   public static final BBacnetEngineeringUnits feetPerMinute = new BBacnetEngineeringUnits(77, "feet per minute");
   public static final BBacnetEngineeringUnits milesPerHour = new BBacnetEngineeringUnits(78, "miles per hour");
   public static final BBacnetEngineeringUnits cubicFeet = new BBacnetEngineeringUnits(79, "cubic foot");
   public static final BBacnetEngineeringUnits cubicMeters = new BBacnetEngineeringUnits(80, "cubic meter");
   public static final BBacnetEngineeringUnits imperialGallons = new BBacnetEngineeringUnits(81, "imperial gallon");
   public static final BBacnetEngineeringUnits liters = new BBacnetEngineeringUnits(82, "liter");
   public static final BBacnetEngineeringUnits usGallons = new BBacnetEngineeringUnits(83, "gallon");
   public static final BBacnetEngineeringUnits cubicFeetPerMinute = new BBacnetEngineeringUnits(84, "cubic feet per minute");
   public static final BBacnetEngineeringUnits cubicMetersPerSecond = new BBacnetEngineeringUnits(85, "cubic meters per second");
   public static final BBacnetEngineeringUnits imperialGallonsPerMinute = new BBacnetEngineeringUnits(86, "imperial gallons per minute");
   public static final BBacnetEngineeringUnits litersPerSecond = new BBacnetEngineeringUnits(87, "liters per second");
   public static final BBacnetEngineeringUnits litersPerMinute = new BBacnetEngineeringUnits(88, "liters per minute");
   public static final BBacnetEngineeringUnits usGallonsPerMinute = new BBacnetEngineeringUnits(89, "gallons per minute");
   public static final BBacnetEngineeringUnits degreesAngular = new BBacnetEngineeringUnits(90, "degrees angular");
   public static final BBacnetEngineeringUnits degreesCelsiusPerHour = new BBacnetEngineeringUnits(91, "degrees celsius per hour");
   public static final BBacnetEngineeringUnits degreesCelsiusPerMinute = new BBacnetEngineeringUnits(92, "degrees celsius per minute");
   public static final BBacnetEngineeringUnits degreesFahrenheitPerHour = new BBacnetEngineeringUnits(93, "degrees fahrenheit per hour");
   public static final BBacnetEngineeringUnits degreesFahrenheitPerMinute = new BBacnetEngineeringUnits(94, "degrees fahrenheit per minute");
   public static final BBacnetEngineeringUnits noUnits = new BBacnetEngineeringUnits(95, "null");
   public static final BBacnetEngineeringUnits partsPerMillion = new BBacnetEngineeringUnits(96, "parts per million");
   public static final BBacnetEngineeringUnits partsPerBillion = new BBacnetEngineeringUnits(97, "parts per billion");
   public static final BBacnetEngineeringUnits percent = new BBacnetEngineeringUnits(98, "percent");
   public static final BBacnetEngineeringUnits percentPerSecond = new BBacnetEngineeringUnits(99, "percent per second");
   public static final BBacnetEngineeringUnits perMinute = new BBacnetEngineeringUnits(100, "per minute");
   public static final BBacnetEngineeringUnits perSecond = new BBacnetEngineeringUnits(101, "per second");
   public static final BBacnetEngineeringUnits psiPerDegreeFahrenheit = new BBacnetEngineeringUnits(102, "psi per degree fahrenheit");
   public static final BBacnetEngineeringUnits radians = new BBacnetEngineeringUnits(103, "radian");
   public static final BBacnetEngineeringUnits revolutionsPerMinute = new BBacnetEngineeringUnits(104, "revolutions per minute");
   public static final BBacnetEngineeringUnits currency1 = new BBacnetEngineeringUnits(105, "currency1");
   public static final BBacnetEngineeringUnits currency2 = new BBacnetEngineeringUnits(106, "currency2");
   public static final BBacnetEngineeringUnits currency3 = new BBacnetEngineeringUnits(107, "currency3");
   public static final BBacnetEngineeringUnits currency4 = new BBacnetEngineeringUnits(108, "currency4");
   public static final BBacnetEngineeringUnits currency5 = new BBacnetEngineeringUnits(109, "currency5");
   public static final BBacnetEngineeringUnits currency6 = new BBacnetEngineeringUnits(110, "currency6");
   public static final BBacnetEngineeringUnits currency7 = new BBacnetEngineeringUnits(111, "currency7");
   public static final BBacnetEngineeringUnits currency8 = new BBacnetEngineeringUnits(112, "currency8");
   public static final BBacnetEngineeringUnits currency9 = new BBacnetEngineeringUnits(113, "currency9");
   public static final BBacnetEngineeringUnits currency10 = new BBacnetEngineeringUnits(114, "currency10");
   public static final BBacnetEngineeringUnits squareInches = new BBacnetEngineeringUnits(115, "square inch");
   public static final BBacnetEngineeringUnits squareCentimeters = new BBacnetEngineeringUnits(116, "square centimeter");
   public static final BBacnetEngineeringUnits btusPerPound = new BBacnetEngineeringUnits(117, "btus per pound");
   public static final BBacnetEngineeringUnits centimeters = new BBacnetEngineeringUnits(118, "centimeter");
   public static final BBacnetEngineeringUnits poundsMassPerSecond = new BBacnetEngineeringUnits(119, "pounds per second");
   public static final BBacnetEngineeringUnits deltaDegreesFahrenheit = new BBacnetEngineeringUnits(120, "fahrenheit degrees");
   public static final BBacnetEngineeringUnits deltaDegreesKelvin = new BBacnetEngineeringUnits(121, "kelvin degrees");
   public static final BBacnetEngineeringUnits kilohms = new BBacnetEngineeringUnits(122, "kilohm");
   public static final BBacnetEngineeringUnits megohms = new BBacnetEngineeringUnits(123, "megohm");
   public static final BBacnetEngineeringUnits millivolts = new BBacnetEngineeringUnits(124, "millivolt");
   public static final BBacnetEngineeringUnits kilojoulesPerKilogram = new BBacnetEngineeringUnits(125, "kilojoules per kilogram");
   public static final BBacnetEngineeringUnits megajoules = new BBacnetEngineeringUnits(126, "megajoule");
   public static final BBacnetEngineeringUnits joulesPerDegreeKelvin = new BBacnetEngineeringUnits(127, "joules per degree kelvin");
   public static final BBacnetEngineeringUnits joulesPerKilogramDegreeKelvin = new BBacnetEngineeringUnits(128, "joules per kilogram degree kelvin");
   public static final BBacnetEngineeringUnits kilohertz = new BBacnetEngineeringUnits(129, "kilohertz");
   public static final BBacnetEngineeringUnits megahertz = new BBacnetEngineeringUnits(130, "megahertz");
   public static final BBacnetEngineeringUnits perHour = new BBacnetEngineeringUnits(131, "per hour");
   public static final BBacnetEngineeringUnits milliwatts = new BBacnetEngineeringUnits(132, "milliwatt");
   public static final BBacnetEngineeringUnits hectopascals = new BBacnetEngineeringUnits(133, "hectopascal");
   public static final BBacnetEngineeringUnits millibars = new BBacnetEngineeringUnits(134, "millibar");
   public static final BBacnetEngineeringUnits cubicMetersPerHour = new BBacnetEngineeringUnits(135, "cubic meters per hour");
   public static final BBacnetEngineeringUnits litersPerHour = new BBacnetEngineeringUnits(136, "liters per hour");
   public static final BBacnetEngineeringUnits kilowattHoursPerSquareMeter = new BBacnetEngineeringUnits(137, "kilowatt hours per square meter");
   public static final BBacnetEngineeringUnits kilowattHoursPerSquareFoot = new BBacnetEngineeringUnits(138, "kilowatt hours per square foot");
   public static final BBacnetEngineeringUnits megajoulesPerSquareMeter = new BBacnetEngineeringUnits(139, "megajoules per square meter");
   public static final BBacnetEngineeringUnits megajoulesPerSquareFoot = new BBacnetEngineeringUnits(140, "megajoules per square foot");
   public static final BBacnetEngineeringUnits wattsPerSquareMeterDegreeKelvin = new BBacnetEngineeringUnits(141, "watts per square meter degree kelvin");
   public static final BBacnetEngineeringUnits cubicFeetPerSecond = new BBacnetEngineeringUnits(142, "cubic feet per second");
   public static final BBacnetEngineeringUnits percentObscurationPerFoot = new BBacnetEngineeringUnits(143, "percent obscuration per foot");
   public static final BBacnetEngineeringUnits percentObscurationPerMeter = new BBacnetEngineeringUnits(144, "percent obscuration per meter");
   public static final BBacnetEngineeringUnits milliohms = new BBacnetEngineeringUnits(145, "milliohm");
   public static final BBacnetEngineeringUnits megawattHours = new BBacnetEngineeringUnits(146, "megawatt hour");
   public static final BBacnetEngineeringUnits kiloBtus = new BBacnetEngineeringUnits(147, "kilobtu");
   public static final BBacnetEngineeringUnits megaBtus = new BBacnetEngineeringUnits(148, "megabtu");
   public static final BBacnetEngineeringUnits kilojoulesPerKilogramDryAir = new BBacnetEngineeringUnits(149, "kilojoules per kilogram dry air");
   public static final BBacnetEngineeringUnits megajoulesPerKilogramDryAir = new BBacnetEngineeringUnits(150, "megajoules per kilogram dry air");
   public static final BBacnetEngineeringUnits kilojoulesPerDegreeKelvin = new BBacnetEngineeringUnits(151, "kilojoules per degree kelvin");
   public static final BBacnetEngineeringUnits megajoulesPerDegreeKelvin = new BBacnetEngineeringUnits(152, "megajoules per degree kelvin");
   public static final BBacnetEngineeringUnits newton = new BBacnetEngineeringUnits(153, "newton");
   public static final BBacnetEngineeringUnits gramsPerSecond = new BBacnetEngineeringUnits(154, "grams per second");
   public static final BBacnetEngineeringUnits gramsPerMinute = new BBacnetEngineeringUnits(155, "grams per minute");
   public static final BBacnetEngineeringUnits tonsPerHour = new BBacnetEngineeringUnits(156, "metric tons per hour");
   public static final BBacnetEngineeringUnits kiloBtusPerHour = new BBacnetEngineeringUnits(157, "kilobtus per hour");
   public static final BBacnetEngineeringUnits hundredthsSeconds = new BBacnetEngineeringUnits(158, "hundredths second");
   public static final BBacnetEngineeringUnits milliseconds = new BBacnetEngineeringUnits(159, "millisecond");
   public static final BBacnetEngineeringUnits newtonMeters = new BBacnetEngineeringUnits(160, "newton meter");
   public static final BBacnetEngineeringUnits millimetersPerSecond = new BBacnetEngineeringUnits(161, "millimeters per second");
   public static final BBacnetEngineeringUnits millimetersPerMinute = new BBacnetEngineeringUnits(162, "millimeters per minute");
   public static final BBacnetEngineeringUnits metersPerMinute = new BBacnetEngineeringUnits(163, "meters per minute");
   public static final BBacnetEngineeringUnits metersPerHour = new BBacnetEngineeringUnits(164, "meters per hour");
   public static final BBacnetEngineeringUnits cubicMetersPerMinute = new BBacnetEngineeringUnits(165, "cubic meters per minute");
   public static final BBacnetEngineeringUnits metersPerSecondPerSecond = new BBacnetEngineeringUnits(166, "meters per second squared");
   public static final BBacnetEngineeringUnits amperesPerMeter = new BBacnetEngineeringUnits(167, "amperes per meter");
   public static final BBacnetEngineeringUnits amperesPerSquareMeter = new BBacnetEngineeringUnits(168, "amperes per square meter");
   public static final BBacnetEngineeringUnits ampereSquareMeters = new BBacnetEngineeringUnits(169, "ampere square meter");
   public static final BBacnetEngineeringUnits farads = new BBacnetEngineeringUnits(170, "farad");
   public static final BBacnetEngineeringUnits henrys = new BBacnetEngineeringUnits(171, "henry");
   public static final BBacnetEngineeringUnits ohmMeters = new BBacnetEngineeringUnits(172, "ohm meter");
   public static final BBacnetEngineeringUnits siemens = new BBacnetEngineeringUnits(173, "siemens");
   public static final BBacnetEngineeringUnits siemensPerMeter = new BBacnetEngineeringUnits(174, "siemens per meter");
   public static final BBacnetEngineeringUnits teslas = new BBacnetEngineeringUnits(175, "tesla");
   public static final BBacnetEngineeringUnits voltsPerDegreeKelvin = new BBacnetEngineeringUnits(176, "volts per degree kelvin");
   public static final BBacnetEngineeringUnits voltsPerMeter = new BBacnetEngineeringUnits(177, "volts per meter");
   public static final BBacnetEngineeringUnits webers = new BBacnetEngineeringUnits(178, "weber");
   public static final BBacnetEngineeringUnits candelas = new BBacnetEngineeringUnits(179, "candela");
   public static final BBacnetEngineeringUnits candelasPerSquareMeter = new BBacnetEngineeringUnits(180, "candelas per square meter");
   public static final BBacnetEngineeringUnits degreesKelvinPerHour = new BBacnetEngineeringUnits(181, "degrees kelvin per hour");
   public static final BBacnetEngineeringUnits degreesKelvinPerMinute = new BBacnetEngineeringUnits(182, "degrees kelvin per minute");
   public static final BBacnetEngineeringUnits jouleSeconds = new BBacnetEngineeringUnits(183, "joule second");
   public static final BBacnetEngineeringUnits radiansPerSecond = new BBacnetEngineeringUnits(184, "radians per second");
   public static final BBacnetEngineeringUnits squareMetersPerNewton = new BBacnetEngineeringUnits(185, "square meters per newton");
   public static final BBacnetEngineeringUnits kilogramsPerCubicMeter = new BBacnetEngineeringUnits(186, "kilograms per cubic meter");
   public static final BBacnetEngineeringUnits newtonSeconds = new BBacnetEngineeringUnits(187, "newton second");
   public static final BBacnetEngineeringUnits newtonsPerMeter = new BBacnetEngineeringUnits(188, "newtons per meter");
   public static final BBacnetEngineeringUnits wattsPerMeterPerDegreeKelvin = new BBacnetEngineeringUnits(189, "watts per meter degree kelvin");
   public static final BBacnetEngineeringUnits microSiemens = new BBacnetEngineeringUnits(190, "microsiemens");
   public static final BBacnetEngineeringUnits cubicFeetPerHour = new BBacnetEngineeringUnits(191, "cubic feet per hour");
   public static final BBacnetEngineeringUnits usGallonsPerHour = new BBacnetEngineeringUnits(192, "gallons per hour");
   public static final BBacnetEngineeringUnits kilometers = new BBacnetEngineeringUnits(193, "kilometer");
   public static final BBacnetEngineeringUnits micrometers = new BBacnetEngineeringUnits(194, "kilometer");
   public static final BBacnetEngineeringUnits grams = new BBacnetEngineeringUnits(195, "gram");
   public static final BBacnetEngineeringUnits milligrams = new BBacnetEngineeringUnits(196, "milligram");
   public static final BBacnetEngineeringUnits milliliters = new BBacnetEngineeringUnits(197, "milliliter");
   public static final BBacnetEngineeringUnits millilitersPerSecond = new BBacnetEngineeringUnits(198, "milliliters per second");
   public static final BBacnetEngineeringUnits decibels = new BBacnetEngineeringUnits(199, "decibel");
   public static final BBacnetEngineeringUnits decibelsMillivolt = new BBacnetEngineeringUnits(200, "db milliVolt");
   public static final BBacnetEngineeringUnits decibelsVolt = new BBacnetEngineeringUnits(201, "db volt");
   public static final BBacnetEngineeringUnits millisiemens = new BBacnetEngineeringUnits(202, "millisiemens");
   public static final BBacnetEngineeringUnits wattHourReactive = new BBacnetEngineeringUnits(203, "watt reactive hour");
   public static final BBacnetEngineeringUnits kilowattHoursReactive = new BBacnetEngineeringUnits(204, "kilowatt reactive hour");
   public static final BBacnetEngineeringUnits megawattHoursReactive = new BBacnetEngineeringUnits(205, "megawatt reactive hour");
   public static final BBacnetEngineeringUnits millilitersOfWater = new BBacnetEngineeringUnits(206, "milliliters of water");
   public static final BBacnetEngineeringUnits perMile = new BBacnetEngineeringUnits(207, "per mile");
   public static final BBacnetEngineeringUnits gramsPerGram = new BBacnetEngineeringUnits(208, "grams per gram");
   public static final BBacnetEngineeringUnits kilogramsPerKilogram = new BBacnetEngineeringUnits(209, "kilograms per kilogram");
   public static final BBacnetEngineeringUnits gramsPerKilogram = new BBacnetEngineeringUnits(210, "grams per kilogram");
   public static final BBacnetEngineeringUnits milligramsPerGram = new BBacnetEngineeringUnits(211, "milligrams per gram");
   public static final BBacnetEngineeringUnits milligramsPerKilogram = new BBacnetEngineeringUnits(212, "milligrams per kilogram");
   public static final BBacnetEngineeringUnits gramsPerMilliliter = new BBacnetEngineeringUnits(213, "grams per milliliter");
   public static final BBacnetEngineeringUnits gramsPerLiter = new BBacnetEngineeringUnits(214, "grams per liter");
   public static final BBacnetEngineeringUnits milligramsPerLiter = new BBacnetEngineeringUnits(215, "milligrams per liter");
   public static final BBacnetEngineeringUnits microgramsPerLiter = new BBacnetEngineeringUnits(216, "micrograms per liter");
   public static final BBacnetEngineeringUnits gramsPerCubicMeter = new BBacnetEngineeringUnits(217, "grams per cubic meter");
   public static final BBacnetEngineeringUnits milligramsPerCubicMeter = new BBacnetEngineeringUnits(218, "milligrams per cubic meter");
   public static final BBacnetEngineeringUnits microgramsPerCubicMeter = new BBacnetEngineeringUnits(219, "micrograms per cubic meter");
   public static final BBacnetEngineeringUnits nanogramsPerCubicMeter = new BBacnetEngineeringUnits(220, "nanograms per cubic meter");
   public static final BBacnetEngineeringUnits gramsPerCubicCentimeter = new BBacnetEngineeringUnits(221, "grams per cubic centimeter");
   public static final BBacnetEngineeringUnits becquerels = new BBacnetEngineeringUnits(222, "becquerel");
   public static final BBacnetEngineeringUnits kilobecquerels = new BBacnetEngineeringUnits(223, "kilobecquerel");
   public static final BBacnetEngineeringUnits megabecquerels = new BBacnetEngineeringUnits(224, "megabecquerel");
   public static final BBacnetEngineeringUnits gray = new BBacnetEngineeringUnits(225, "gray");
   public static final BBacnetEngineeringUnits milligray = new BBacnetEngineeringUnits(226, "milligray");
   public static final BBacnetEngineeringUnits microgray = new BBacnetEngineeringUnits(227, "microgray");
   public static final BBacnetEngineeringUnits sieverts = new BBacnetEngineeringUnits(228, "sievert");
   public static final BBacnetEngineeringUnits millisieverts = new BBacnetEngineeringUnits(229, "millisievert");
   public static final BBacnetEngineeringUnits microsieverts = new BBacnetEngineeringUnits(230, "microsievert");
   public static final BBacnetEngineeringUnits microsievertsPerHour = new BBacnetEngineeringUnits(231, "microsievert per hour");
   public static final BBacnetEngineeringUnits decibelsA = new BBacnetEngineeringUnits(232, "db ampere");
   public static final BBacnetEngineeringUnits nephelometricTurbidityUnit = new BBacnetEngineeringUnits(233, "nephelometric turbidity units");
   public static final BBacnetEngineeringUnits ph = new BBacnetEngineeringUnits(234, "pH");
   public static final BBacnetEngineeringUnits gramsPerSquareMeter = new BBacnetEngineeringUnits(235, "grams per square meter");
   public static final BBacnetEngineeringUnits minutesPerDegreeKelvin = new BBacnetEngineeringUnits(236, "minutes per degree kelvin");
   public static final BBacnetEngineeringUnits ohmMeterSquaredPerMeter = new BBacnetEngineeringUnits(237, "ohm meter squared per meter");
   public static final BBacnetEngineeringUnits ampereSeconds = new BBacnetEngineeringUnits(238, "ampere seconds");
   public static final BBacnetEngineeringUnits voltAmpereHour = new BBacnetEngineeringUnits(239, "volt ampere hour");
   public static final BBacnetEngineeringUnits kilovoltAmpereHour = new BBacnetEngineeringUnits(240, "kilovolt ampere hour");
   public static final BBacnetEngineeringUnits megavoltAmpereHour = new BBacnetEngineeringUnits(241, "megavolt ampere hour");
   public static final BBacnetEngineeringUnits voltAmpereReactiveHour = new BBacnetEngineeringUnits(242, "volt ampere reactive hour");
   public static final BBacnetEngineeringUnits kilovoltAmpereReactiveHour = new BBacnetEngineeringUnits(243, "kilovolt ampere reactive hour");
   public static final BBacnetEngineeringUnits megavoltAmpereReactiveHour = new BBacnetEngineeringUnits(244, "megavolt ampere reactive hour");
   public static final BBacnetEngineeringUnits voltSquaredHours = new BBacnetEngineeringUnits(245, "volt squared hours");
   public static final BBacnetEngineeringUnits ampereSquaredHours = new BBacnetEngineeringUnits(246, "ampere squared hours");
   public static final BBacnetEngineeringUnits joulesPerHour = new BBacnetEngineeringUnits(247, "joules per hour");
   public static final BBacnetEngineeringUnits cubicFeetPerDay = new BBacnetEngineeringUnits(248, "cubic feet per day");
   public static final BBacnetEngineeringUnits cubicMetersPerDay = new BBacnetEngineeringUnits(249, "cubic meters per day");
   public static final BBacnetEngineeringUnits wattHourPerCubicMeter = new BBacnetEngineeringUnits(250, "watt hour per cubic meter");
   public static final BBacnetEngineeringUnits joulesPerCubicMeter = new BBacnetEngineeringUnits(251, "joules per cubic meter");
   public static final BBacnetEngineeringUnits molesPercent = new BBacnetEngineeringUnits(252, "moles percent");
   public static final BBacnetEngineeringUnits pascalSecond = new BBacnetEngineeringUnits(253, "pascal second");
   public static final BBacnetEngineeringUnits millionStandardCubicFeetPerMinute = new BBacnetEngineeringUnits(254, "million standard cubic feet per minute");
   public static final BBacnetEngineeringUnits standardCubicFeetPerDay = new BBacnetEngineeringUnits(47808, "standard cubic feet per day");
   public static final BBacnetEngineeringUnits millionStandardCubicFeetPerDay = new BBacnetEngineeringUnits(47809, "million standard cubic feet per day");
   public static final BBacnetEngineeringUnits thousandCubicFeetPerDay = new BBacnetEngineeringUnits(47810, "thousand cubic feet per day");
   public static final BBacnetEngineeringUnits thousandStandardCubicFeetPerDay = new BBacnetEngineeringUnits(47811, "thousand standard cubic feet per day");
   public static final BBacnetEngineeringUnits poundsMassPerDay = new BBacnetEngineeringUnits(47812, "pounds mass per day");
   public static final BBacnetEngineeringUnits millirems = new BBacnetEngineeringUnits(47814, "millirems");
   public static final BBacnetEngineeringUnits milliremsPerHour = new BBacnetEngineeringUnits(47815, "millirems per hour");
   public static final BBacnetEngineeringUnits DEFAULT = squareMeters;
   public static final Type TYPE = Sys.loadType(BBacnetEngineeringUnits.class);
   public static final int MAX_ASHRAE_ID = 254;
   public static final int MAX_RESERVED_ID = 255;
   public static final int MAX_ID = 65535;
   public static final int ASHRAE_RESERVED_RANGE_MIN = 47808;
   public static final int ASHRAE_RESERVED_RANGE_MAX = 49999;
   private String niagaraName;
   private static HashMap<BUnit, BBacnetEngineeringUnits> map = new HashMap<>();
   private static final Logger logger = Logger.getLogger("bacnet.enums");

   public static BBacnetEngineeringUnits make(int ordinal) {
      return (BBacnetEngineeringUnits)squareMeters.getRange().get(ordinal, false);
   }

   public static BBacnetEngineeringUnits make(String tag) {
      return (BBacnetEngineeringUnits)squareMeters.getRange().get(tag);
   }

   public Type getType() {
      return TYPE;
   }

   public static BBacnetEngineeringUnits make(BUnit niagaraUnits) {
      if (niagaraUnits == null) {
         return noUnits;
      } else {
         BBacnetEngineeringUnits bacnetUnits = map.get(niagaraUnits);
         return bacnetUnits == null ? noUnits : bacnetUnits;
      }
   }

   private BBacnetEngineeringUnits(int ordinal, String niagaraName) {
      super(ordinal);
      this.niagaraName = niagaraName;
   }

   public static String tag(int id) {
      if (DEFAULT.getRange().isOrdinal(id)) {
         return DEFAULT.getRange().getTag(id);
      } else if (isAshrae(id)) {
         return ASHRAE_PREFIX + id;
      } else if (isProprietary(id)) {
         return PROPRIETARY_PREFIX + id;
      } else {
         throw new InvalidEnumException(id);
      }
   }

   public static int ordinal(String tag) {
      try {
         return DEFAULT.getRange().tagToOrdinal(tag);
      } catch (InvalidEnumException var2) {
         if (tag.startsWith(ASHRAE_PREFIX)) {
            return Integer.parseInt(tag.substring(ASHRAE_PREFIX_LENGTH));
         } else if (tag.startsWith(PROPRIETARY_PREFIX)) {
            return Integer.parseInt(tag.substring(PROPRIETARY_PREFIX_LENGTH));
         } else {
            throw var2;
         }
      }
   }

   public static boolean isProprietary(int id) {
      return id > 255 && id <= 65535 && !isAshraeExtended(id);
   }

   public static boolean isAshrae(int id) {
      return id > 254 && id <= 255;
   }

   public static boolean isAshraeExtended(int id) {
      return id >= 47808 && id <= 49999;
   }

   public static boolean isValid(int id) {
      return id <= 65535;
   }

   public static boolean isFixed(int id) {
      return id <= 254;
   }

   public BUnit getNiagaraUnits() {
      if (this.niagaraName == null) {
         return null;
      } else {
         try {
            return BUnit.getUnit(this.niagaraName);
         } catch (UnitException var2) {
            logger.warning("Unknown Unit: " + this.niagaraName);
            return null;
         }
      }
   }

   public String toString(Context context) {
      return context != null && context.equals(BacnetConst.facetsContext) ? this.getTag() : this.getDisplayTag(context);
   }

   public static BUnit getNiagaraUnits(int ordinal) {
      return isFixed(ordinal) ? make(ordinal).getNiagaraUnits() : null;
   }

   static {
      UnitDatabase.getDefault();
      map.put(BUnit.getUnit("square meter"), squareMeters);
      map.put(BUnit.getUnit("square foot"), squareFeet);
      map.put(BUnit.getUnit("milliampere"), milliamperes);
      map.put(BUnit.getUnit("ampere"), amperes);
      map.put(BUnit.getUnit("ohm"), ohms);
      map.put(BUnit.getUnit("volt"), volts);
      map.put(BUnit.getUnit("kilovolt"), kilovolts);
      map.put(BUnit.getUnit("megavolt"), megavolts);
      map.put(BUnit.getUnit("volt ampere"), voltAmperes);
      map.put(BUnit.getUnit("kilovolt ampere"), kilovoltAmperes);
      map.put(BUnit.getUnit("megavolt ampere"), megavoltAmperes);
      map.put(BUnit.getUnit("volt ampere reactive"), voltAmperesReactive);
      map.put(BUnit.getUnit("kilovolt ampere reactive"), kilovoltAmperesReactive);
      map.put(BUnit.getUnit("megavolt ampere reactive"), megavoltAmperesReactive);
      map.put(BUnit.getUnit("degrees phase"), degreesPhase);
      map.put(BUnit.getUnit("power factor"), powerFactor);
      map.put(BUnit.getUnit("joule"), joules);
      map.put(BUnit.getUnit("kilojoule"), kilojoules);
      map.put(BUnit.getUnit("watt hour"), wattHours);
      map.put(BUnit.getUnit("kilowatt hour"), kilowattHours);
      map.put(BUnit.getUnit("btu"), btus);
      map.put(BUnit.getUnit("therm"), therms);
      map.put(BUnit.getUnit("tons refrigeration hour"), tonHours);
      map.put(BUnit.getUnit("joules per kilogram dry air"), joulesPerKilogramDryAir);
      map.put(BUnit.getUnit("btus per pound dry air"), btusPerPoundDryAir);
      map.put(BUnit.getUnit("cycles per hour"), cyclesPerHour);
      map.put(BUnit.getUnit("cycles per minute"), cyclesPerMinute);
      map.put(BUnit.getUnit("hertz"), hertz);
      map.put(BUnit.getUnit("grams of water per kilogram dry air"), gramsOfWaterPerKilogramDryAir);
      map.put(BUnit.getUnit("percent relative humidity"), percentRelativeHumidity);
      map.put(BUnit.getUnit("millimeter"), millimeters);
      map.put(BUnit.getUnit("meter"), meters);
      map.put(BUnit.getUnit("inch"), inches);
      map.put(BUnit.getUnit("foot"), feet);
      map.put(BUnit.getUnit("watts per square foot"), wattsPerSquareFoot);
      map.put(BUnit.getUnit("watts per square meter"), wattsPerSquareMeter);
      map.put(BUnit.getUnit("lumen"), lumens);
      map.put(BUnit.getUnit("lux"), luxes);
      map.put(BUnit.getUnit("footcandle"), footCandles);
      map.put(BUnit.getUnit("kilogram"), kilograms);
      map.put(BUnit.getUnit("pound"), poundsMass);
      map.put(BUnit.getUnit("metric ton"), tons);
      map.put(BUnit.getUnit("kilograms per second"), kilogramsPerSecond);
      map.put(BUnit.getUnit("kilograms per minute"), kilogramsPerMinute);
      map.put(BUnit.getUnit("kilograms per hour"), kilogramsPerHour);
      map.put(BUnit.getUnit("pounds per minute"), poundsMassPerMinute);
      map.put(BUnit.getUnit("pounds per hour"), poundsMassPerHour);
      map.put(BUnit.getUnit("watt"), watts);
      map.put(BUnit.getUnit("kilowatt"), kilowatts);
      map.put(BUnit.getUnit("megawatt"), megawatts);
      map.put(BUnit.getUnit("btus per hour"), btusPerHour);
      map.put(BUnit.getUnit("horsepower"), horsepower);
      map.put(BUnit.getUnit("tons refrigeration"), tonsRefrigeration);
      map.put(BUnit.getUnit("pascal"), pascals);
      map.put(BUnit.getUnit("kilopascal"), kilopascals);
      map.put(BUnit.getUnit("bar"), bars);
      map.put(BUnit.getUnit("pounds per square inch"), poundsForcePerSquareInch);
      map.put(BUnit.getUnit("centimeters of water"), centimetersOfWater);
      map.put(BUnit.getUnit("inches of water"), inchesOfWater);
      map.put(BUnit.getUnit("millimeters of mercury"), millimetersOfMercury);
      map.put(BUnit.getUnit("centimeters of mercury"), centimetersOfMercury);
      map.put(BUnit.getUnit("inches of mercury"), inchesOfMercury);
      map.put(BUnit.getUnit("celsius"), degreesCelsius);
      map.put(BUnit.getUnit("kelvin"), degreesKelvin);
      map.put(BUnit.getUnit("fahrenheit"), degreesFahrenheit);
      map.put(BUnit.getUnit("degree days celsius"), degreeDaysCelsius);
      map.put(BUnit.getUnit("degree days fahrenheit"), degreeDaysFahrenheit);
      map.put(BUnit.getUnit("year"), years);
      map.put(BUnit.getUnit("julian month"), months);
      map.put(BUnit.getUnit("week"), weeks);
      map.put(BUnit.getUnit("day"), days);
      map.put(BUnit.getUnit("hour"), hours);
      map.put(BUnit.getUnit("minute"), minutes);
      map.put(BUnit.getUnit("second"), seconds);
      map.put(BUnit.getUnit("meters per second"), metersPerSecond);
      map.put(BUnit.getUnit("kilometers per hour"), kilometersPerHour);
      map.put(BUnit.getUnit("feet per second"), feetPerSecond);
      map.put(BUnit.getUnit("feet per minute"), feetPerMinute);
      map.put(BUnit.getUnit("miles per hour"), milesPerHour);
      map.put(BUnit.getUnit("cubic foot"), cubicFeet);
      map.put(BUnit.getUnit("cubic meter"), cubicMeters);
      map.put(BUnit.getUnit("imperial gallon"), imperialGallons);
      map.put(BUnit.getUnit("liter"), liters);
      map.put(BUnit.getUnit("gallon"), usGallons);
      map.put(BUnit.getUnit("cubic feet per minute"), cubicFeetPerMinute);
      map.put(BUnit.getUnit("cubic meters per second"), cubicMetersPerSecond);
      map.put(BUnit.getUnit("imperial gallons per minute"), imperialGallonsPerMinute);
      map.put(BUnit.getUnit("liters per second"), litersPerSecond);
      map.put(BUnit.getUnit("liters per minute"), litersPerMinute);
      map.put(BUnit.getUnit("gallons per minute"), usGallonsPerMinute);
      map.put(BUnit.getUnit("degrees angular"), degreesAngular);
      map.put(BUnit.getUnit("degrees celsius per hour"), degreesCelsiusPerHour);
      map.put(BUnit.getUnit("degrees celsius per minute"), degreesCelsiusPerMinute);
      map.put(BUnit.getUnit("degrees fahrenheit per hour"), degreesFahrenheitPerHour);
      map.put(BUnit.getUnit("degrees fahrenheit per minute"), degreesFahrenheitPerMinute);
      map.put(BUnit.getUnit("null"), noUnits);
      map.put(BUnit.getUnit("parts per million"), partsPerMillion);
      map.put(BUnit.getUnit("parts per billion"), partsPerBillion);
      map.put(BUnit.getUnit("percent"), percent);
      map.put(BUnit.getUnit("percent per second"), percentPerSecond);
      map.put(BUnit.getUnit("per minute"), perMinute);
      map.put(BUnit.getUnit("per second"), perSecond);
      map.put(BUnit.getUnit("psi per degree fahrenheit"), psiPerDegreeFahrenheit);
      map.put(BUnit.getUnit("radian"), radians);
      map.put(BUnit.getUnit("revolutions per minute"), revolutionsPerMinute);
      map.put(BUnit.getUnit("currency1"), currency1);
      map.put(BUnit.getUnit("currency2"), currency2);
      map.put(BUnit.getUnit("currency3"), currency3);
      map.put(BUnit.getUnit("currency4"), currency4);
      map.put(BUnit.getUnit("currency5"), currency5);
      map.put(BUnit.getUnit("currency6"), currency6);
      map.put(BUnit.getUnit("currency7"), currency7);
      map.put(BUnit.getUnit("currency8"), currency8);
      map.put(BUnit.getUnit("currency9"), currency9);
      map.put(BUnit.getUnit("currency10"), currency10);
      map.put(BUnit.getUnit("square inch"), squareInches);
      map.put(BUnit.getUnit("square centimeter"), squareCentimeters);
      map.put(BUnit.getUnit("btus per pound"), btusPerPound);
      map.put(BUnit.getUnit("centimeter"), centimeters);
      map.put(BUnit.getUnit("pounds per second"), poundsMassPerSecond);
      map.put(BUnit.getUnit("fahrenheit degrees"), deltaDegreesFahrenheit);
      map.put(BUnit.getUnit("kelvin degrees"), deltaDegreesKelvin);
      map.put(BUnit.getUnit("kilohm"), kilohms);
      map.put(BUnit.getUnit("megohm"), megohms);
      map.put(BUnit.getUnit("millivolt"), millivolts);
      map.put(BUnit.getUnit("kilojoules per kilogram"), kilojoulesPerKilogram);
      map.put(BUnit.getUnit("megajoule"), megajoules);
      map.put(BUnit.getUnit("joules per degree kelvin"), joulesPerDegreeKelvin);
      map.put(BUnit.getUnit("joules per kilogram degree kelvin"), joulesPerKilogramDegreeKelvin);
      map.put(BUnit.getUnit("kilohertz"), kilohertz);
      map.put(BUnit.getUnit("megahertz"), megahertz);
      map.put(BUnit.getUnit("per hour"), perHour);
      map.put(BUnit.getUnit("milliwatt"), milliwatts);
      map.put(BUnit.getUnit("hectopascal"), hectopascals);
      map.put(BUnit.getUnit("millibar"), millibars);
      map.put(BUnit.getUnit("cubic meters per hour"), cubicMetersPerHour);
      map.put(BUnit.getUnit("liters per hour"), litersPerHour);
      map.put(BUnit.getUnit("kilowatt hours per square meter"), kilowattHoursPerSquareMeter);
      map.put(BUnit.getUnit("kilowatt hours per square foot"), kilowattHoursPerSquareFoot);
      map.put(BUnit.getUnit("megajoules per square meter"), megajoulesPerSquareMeter);
      map.put(BUnit.getUnit("megajoules per square foot"), megajoulesPerSquareFoot);
      map.put(BUnit.getUnit("watts per square meter degree kelvin"), wattsPerSquareMeterDegreeKelvin);
      map.put(BUnit.getUnit("cubic feet per second"), cubicFeetPerSecond);
      map.put(BUnit.getUnit("percent obscuration per foot"), percentObscurationPerFoot);
      map.put(BUnit.getUnit("percent obscuration per meter"), percentObscurationPerMeter);
      map.put(BUnit.getUnit("milliohm"), milliohms);
      map.put(BUnit.getUnit("megawatt hour"), megawattHours);
      map.put(BUnit.getUnit("kilobtu"), kiloBtus);
      map.put(BUnit.getUnit("megabtu"), megaBtus);
      map.put(BUnit.getUnit("kilojoules per kilogram dry air"), kilojoulesPerKilogramDryAir);
      map.put(BUnit.getUnit("megajoules per kilogram dry air"), megajoulesPerKilogramDryAir);
      map.put(BUnit.getUnit("kilojoules per degree kelvin"), kilojoulesPerDegreeKelvin);
      map.put(BUnit.getUnit("megajoules per degree kelvin"), megajoulesPerDegreeKelvin);
      map.put(BUnit.getUnit("newton"), newton);
      map.put(BUnit.getUnit("grams per second"), gramsPerSecond);
      map.put(BUnit.getUnit("grams per minute"), gramsPerMinute);
      map.put(BUnit.getUnit("metric tons per hour"), tonsPerHour);
      map.put(BUnit.getUnit("kilobtus per hour"), kiloBtusPerHour);
      map.put(BUnit.getUnit("hundredths second"), hundredthsSeconds);
      map.put(BUnit.getUnit("millisecond"), milliseconds);
      map.put(BUnit.getUnit("newton meter"), newtonMeters);
      map.put(BUnit.getUnit("millimeters per second"), millimetersPerSecond);
      map.put(BUnit.getUnit("millimeters per minute"), millimetersPerMinute);
      map.put(BUnit.getUnit("meters per minute"), metersPerMinute);
      map.put(BUnit.getUnit("meters per hour"), metersPerHour);
      map.put(BUnit.getUnit("cubic meters per minute"), cubicMetersPerMinute);
      map.put(BUnit.getUnit("meters per second squared"), metersPerSecondPerSecond);
      map.put(BUnit.getUnit("amperes per meter"), amperesPerMeter);
      map.put(BUnit.getUnit("amperes per square meter"), amperesPerSquareMeter);
      map.put(BUnit.getUnit("ampere square meter"), ampereSquareMeters);
      map.put(BUnit.getUnit("farad"), farads);
      map.put(BUnit.getUnit("henry"), henrys);
      map.put(BUnit.getUnit("ohm meter"), ohmMeters);
      map.put(BUnit.getUnit("siemens"), siemens);
      map.put(BUnit.getUnit("siemens per meter"), siemensPerMeter);
      map.put(BUnit.getUnit("tesla"), teslas);
      map.put(BUnit.getUnit("volts per degree kelvin"), voltsPerDegreeKelvin);
      map.put(BUnit.getUnit("volts per meter"), voltsPerMeter);
      map.put(BUnit.getUnit("weber"), webers);
      map.put(BUnit.getUnit("candela"), candelas);
      map.put(BUnit.getUnit("candelas per square meter"), candelasPerSquareMeter);
      map.put(BUnit.getUnit("degrees kelvin per hour"), degreesKelvinPerHour);
      map.put(BUnit.getUnit("degrees kelvin per minute"), degreesKelvinPerMinute);
      map.put(BUnit.getUnit("joule second"), jouleSeconds);
      map.put(BUnit.getUnit("radians per second"), radiansPerSecond);
      map.put(BUnit.getUnit("square meters per newton"), squareMetersPerNewton);
      map.put(BUnit.getUnit("kilograms per cubic meter"), kilogramsPerCubicMeter);
      map.put(BUnit.getUnit("newton second"), newtonSeconds);
      map.put(BUnit.getUnit("newtons per meter"), newtonsPerMeter);
      map.put(BUnit.getUnit("watts per meter degree kelvin"), wattsPerMeterPerDegreeKelvin);
      map.put(BUnit.getUnit("microsiemens"), microSiemens);
      map.put(BUnit.getUnit("cubic feet per hour"), cubicFeetPerHour);
      map.put(BUnit.getUnit("gallons per hour"), usGallonsPerHour);
      map.put(BUnit.getUnit("kilometer"), kilometers);
      map.put(BUnit.getUnit("micrometer"), micrometers);
      map.put(BUnit.getUnit("gram"), grams);
      map.put(BUnit.getUnit("milligram"), milligrams);
      map.put(BUnit.getUnit("milliliter"), milliliters);
      map.put(BUnit.getUnit("milliliters per second"), millilitersPerSecond);
      map.put(BUnit.getUnit("decibel"), decibels);
      map.put(BUnit.getUnit("db milliVolt"), decibelsMillivolt);
      map.put(BUnit.getUnit("db volt"), decibelsVolt);
      map.put(BUnit.getUnit("millisiemens"), millisiemens);
      map.put(BUnit.getUnit("watt reactive hour"), wattHourReactive);
      map.put(BUnit.getUnit("kilowatt reactive hour"), kilowattHoursReactive);
      map.put(BUnit.getUnit("megawatt reactive hour"), megawattHoursReactive);
      map.put(BUnit.getUnit("milliliters of water"), millilitersOfWater);
      map.put(BUnit.getUnit("per mile"), perMile);
      map.put(BUnit.getUnit("grams per gram"), gramsPerGram);
      map.put(BUnit.getUnit("kilograms per kilogram"), kilogramsPerKilogram);
      map.put(BUnit.getUnit("grams per kilogram"), gramsPerKilogram);
      map.put(BUnit.getUnit("milligrams per gram"), milligramsPerGram);
      map.put(BUnit.getUnit("milligrams per kilogram"), milligramsPerKilogram);
      map.put(BUnit.getUnit("grams per milliliter"), gramsPerMilliliter);
      map.put(BUnit.getUnit("grams per liter"), gramsPerLiter);
      map.put(BUnit.getUnit("milligrams per liter"), milligramsPerLiter);
      map.put(BUnit.getUnit("micrograms per liter"), microgramsPerLiter);
      map.put(BUnit.getUnit("grams per cubic meter"), gramsPerCubicMeter);
      map.put(BUnit.getUnit("milligrams per cubic meter"), milligramsPerCubicMeter);
      map.put(BUnit.getUnit("micrograms per cubic meter"), microgramsPerCubicMeter);
      map.put(BUnit.getUnit("nanograms per cubic meter"), nanogramsPerCubicMeter);
      map.put(BUnit.getUnit("grams per cubic centimeter"), gramsPerCubicCentimeter);
      map.put(BUnit.getUnit("becquerel"), becquerels);
      map.put(BUnit.getUnit("kilobecquerel"), kilobecquerels);
      map.put(BUnit.getUnit("megabecquerel"), megabecquerels);
      map.put(BUnit.getUnit("gray"), gray);
      map.put(BUnit.getUnit("milligray"), milligray);
      map.put(BUnit.getUnit("microgray"), microgray);
      map.put(BUnit.getUnit("sievert"), sieverts);
      map.put(BUnit.getUnit("millisievert"), millisieverts);
      map.put(BUnit.getUnit("microsievert"), microsieverts);
      map.put(BUnit.getUnit("microsievert per hour"), microsievertsPerHour);
      map.put(BUnit.getUnit("db ampere"), decibelsA);
      map.put(BUnit.getUnit("nephelometric turbidity units"), nephelometricTurbidityUnit);
      map.put(BUnit.getUnit("pH"), ph);
      map.put(BUnit.getUnit("grams per square meter"), gramsPerSquareMeter);
      map.put(BUnit.getUnit("minutes per degree kelvin"), minutesPerDegreeKelvin);
      map.put(BUnit.getUnit("ohm meter squared per meter"), ohmMeterSquaredPerMeter);
      map.put(BUnit.getUnit("ampere seconds"), ampereSeconds);
      map.put(BUnit.getUnit("volt ampere hour"), voltAmpereHour);
      map.put(BUnit.getUnit("kilovolt ampere hour"), kilovoltAmpereHour);
      map.put(BUnit.getUnit("megavolt ampere hour"), megavoltAmpereHour);
      map.put(BUnit.getUnit("volt ampere reactive hour"), voltAmpereReactiveHour);
      map.put(BUnit.getUnit("kilovolt ampere reactive hour"), kilovoltAmpereReactiveHour);
      map.put(BUnit.getUnit("megavolt ampere reactive hour"), megavoltAmpereReactiveHour);
      map.put(BUnit.getUnit("volt squared hours"), voltSquaredHours);
      map.put(BUnit.getUnit("ampere squared hours"), ampereSquaredHours);
      map.put(BUnit.getUnit("joules per hour"), joulesPerHour);
      map.put(BUnit.getUnit("cubic feet per day"), cubicFeetPerDay);
      map.put(BUnit.getUnit("cubic meters per day"), cubicMetersPerDay);
      map.put(BUnit.getUnit("watt hour per cubic meter"), wattHourPerCubicMeter);
      map.put(BUnit.getUnit("joules per cubic meter"), joulesPerCubicMeter);
      map.put(BUnit.getUnit("moles percent"), molesPercent);
      map.put(BUnit.getUnit("pascal second"), pascalSecond);
      map.put(BUnit.getUnit("million standard cubic feet per minute"), millionStandardCubicFeetPerMinute);
      map.put(BUnit.getUnit("standard cubic feet per day"), standardCubicFeetPerDay);
      map.put(BUnit.getUnit("million standard cubic feet per day"), millionStandardCubicFeetPerDay);
      map.put(BUnit.getUnit("thousand cubic feet per day"), thousandCubicFeetPerDay);
      map.put(BUnit.getUnit("thousand standard cubic feet per day"), thousandStandardCubicFeetPerDay);
      map.put(BUnit.getUnit("pounds mass per day"), poundsMassPerDay);
      map.put(BUnit.getUnit("millirems"), millirems);
      map.put(BUnit.getUnit("millirems per hour"), milliremsPerHour);
   }
}
