package com.tridium.bacnet.stack.link.ip;

public interface BvllConst {
   int BVLC_TYPE_BACNET_IP = 129;
   int BVLL_LENGTH_OFFSET = 2;
   int BVLL_BASE_LENGTH = 4;
   int BVLC_RESULT = 0;
   int WRITE_BROADCAST_DISTRIBUTION_TABLE = 1;
   int READ_BROADCAST_DISTRIBUTION_TABLE = 2;
   int READ_BROADCAST_DISTRIBUTION_TABLE_ACK = 3;
   int FORWARDED_NPDU = 4;
   int REGISTER_FOREIGN_DEVICE = 5;
   int READ_FOREIGN_DEVICE_TABLE = 6;
   int READ_FOREIGN_DEVICE_TABLE_ACK = 7;
   int DELETE_FOREIGN_DEVICE_TABLE_ENTRY = 8;
   int DISTRIBUTE_BROADCAST_TO_NETWORK = 9;
   int ORIGINAL_UNICAST_NPDU = 10;
   int ORIGINAL_BROADCAST_NPDU = 11;
}
