#!/usr/bin/env python3
"""
corpus-nav.py — Navigate the niagara-research knowledge corpus.

Python 3 stdlib ONLY. Deterministic, sorted output. No external deps, no DB.

The corpus (all paths relative to the repo root, resolved from this script):
  - Blocks:  niagara-mental-model-bloque<N>.md  (N is a GLOBAL block number with
             historical gaps), plus the consolidated niagara-mental-model.md
             (label "1-3") and niagara-mental-model-bloque-test-infrastructure.md
             (label "TI").
  - CATALOG.md — AUTOGENERATED authoritative index. Each row is
             `| <label> | [file](file) | <title> |`. Source of truth for the
             block <-> title map. This tool NEVER edits it.
  - docs/*.md    — synthesis guides.
  - retros/*.md  — retrospectives.
  - RESEARCH-STATE-<focus>.md — per-focus state files.

Subcommands:
  find <query>        full-text (case-insensitive substring) search
  grep <regex>        regex search (re module)
  show <N>            H1 + section outline + Connections of block B<N>
  list                all blocks as `B<N> · <title>` (from CATALOG.md)
  by-marker <marker>  blocks containing an evidence marker (INFER, CERT-hw, ...)
  by-focus <focus>    blocks belonging to a focus (see heuristic below)
  connections <N>     forward + reverse block links for B<N>
  stats               corpus totals + marker counts

Run `corpus-nav.py <cmd> -h` for per-command flags.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Repository layout — always relative to this script's location.
# tools/corpus-nav.py  ->  repo root is the parent of tools/.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "CATALOG.md"
DOCS_DIR = REPO_ROOT / "docs"
RETROS_DIR = REPO_ROOT / "retros"

# Snapshot block files excluded from the active corpus (mirrors gen-catalog.py).
SNAPSHOTS = {"niagara-mental-model.2026-04-19.md"}

# ---------------------------------------------------------------------------
# Evidence markers: [CERT], [CERT-hw], [CERT-live], [CERT-doc], [CERT-web],
# [INFER], and combined forms like [CERT-doc/INFER]. A bracket token may hold
# several slash-separated components; each component is one marker instance.
# ---------------------------------------------------------------------------
_MARKER_TOKEN_RE = re.compile(r"\[((?:CERT|INFER)[\w/-]*)\]")

# ---------------------------------------------------------------------------
# Block references used inside prose / Connections. Observed forms across the
# corpus (frequency order): [Block N] (dominant), [Bloque N], [BN], bloqueN.
# `[Bloque #N]` also appears. We capture the numeric N from any of them.
# ---------------------------------------------------------------------------
_REF_RE = re.compile(
    r"\[B(?:lock|loque)\s+#?(\d+)\]"  # [Block 18] / [Bloque 75] / [Bloque #12]
    r"|\[B(\d+)\]"                     # [B722]
    r"|\bbloque(\d+)\b",              # bloque106
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Block file discovery + numbering (robust to historical gaps: nothing here
# assumes N is contiguous — we only ever use the labels we actually find).
# ---------------------------------------------------------------------------
_BLOCK_NUM_RE = re.compile(r"^niagara-mental-model-bloque(\d+)\.md$")


def block_label_for_file(name: str) -> str | None:
    """Return the block label for a corpus filename, or None if not a block.

    Numeric blocks -> str(N); consolidated file -> "1-3"; TI file -> "TI".
    """
    if name in SNAPSHOTS:
        return None
    if name == "niagara-mental-model.md":
        return "1-3"
    if name == "niagara-mental-model-bloque-test-infrastructure.md":
        return "TI"
    m = _BLOCK_NUM_RE.match(name)
    if m:
        return str(int(m.group(1)))
    return None


def label_sort_key(label: str) -> tuple[int, int]:
    """Deterministic ordering: consolidated first, numeric by value, TI last."""
    if label == "1-3":
        return (0, 0)
    if label == "TI":
        return (2, 0)
    return (1, int(label))


def display_id(label: str) -> str:
    """Human id used throughout output: B720, B1-3, BTI."""
    return f"B{label}"


def iter_block_files() -> list[tuple[str, Path]]:
    """All active block files as (label, path), sorted deterministically."""
    out: list[tuple[str, Path]] = []
    for path in REPO_ROOT.glob("niagara-mental-model*.md"):
        label = block_label_for_file(path.name)
        if label is not None:
            out.append((label, path))
    out.sort(key=lambda t: label_sort_key(t[0]))
    return out


def iter_dir_files(directory: Path) -> list[Path]:
    """Sorted *.md files directly under a directory (docs/, retros/)."""
    if not directory.is_dir():
        return []
    return sorted(directory.glob("*.md"))


# ---------------------------------------------------------------------------
# CATALOG.md parsing — source of truth for label -> title.
# Rows look like: `| 720 | [file](file) | title |`
# ---------------------------------------------------------------------------
_CATALOG_ROW_RE = re.compile(r"^\|\s*([^|]+?)\s*\|\s*\[[^\]]+\]\([^)]+\)\s*\|\s*(.*?)\s*\|\s*$")


def load_catalog() -> dict[str, str]:
    """Parse CATALOG.md into {label: title}. Empty dict if file is missing."""
    titles: dict[str, str] = {}
    if not CATALOG_PATH.is_file():
        return titles
    for line in CATALOG_PATH.read_text(encoding="utf-8").splitlines():
        m = _CATALOG_ROW_RE.match(line)
        if not m:
            continue
        label, title = m.group(1).strip(), m.group(2).strip()
        # Skip the header separator / header row.
        if label in ("Bloque", "--------") or set(label) <= {"-"}:
            continue
        titles[label] = title
    return titles


# ---------------------------------------------------------------------------
# Per-block text helpers
# ---------------------------------------------------------------------------
def read_h1(path: Path) -> str:
    """First H1 line ('# ...') from a file, stripped of the leading '# '."""
    try:
        with path.open(encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s.startswith("# "):
                    return s[2:].strip()
    except OSError:
        pass
    return ""


def title_for(label: str, catalog: dict[str, str], path: Path) -> str:
    """CATALOG title if present, else the block's own H1, else '(no title)'."""
    return catalog.get(label) or read_h1(path) or "(no title)"


def extract_section(path: Path, header_names: tuple[str, ...]) -> list[str]:
    """Return the lines of a '## <name>' section (until the next '## ' heading).

    Matching on the header text is case-insensitive; header_names are the
    accepted heading titles (e.g. ('Connections',)).
    """
    wanted = {h.lower() for h in header_names}
    lines = path.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.startswith("## "):
            if capturing:
                break  # reached the next section
            capturing = line[3:].strip().lower() in wanted
            continue
        if capturing:
            out.append(line)
    return out


def refs_in_text(text: str) -> set[int]:
    """All block numbers referenced in a chunk of text."""
    nums: set[int] = set()
    for m in _REF_RE.finditer(text):
        for g in m.groups():
            if g:
                nums.add(int(g))
    return nums


# ---------------------------------------------------------------------------
# Focus membership (by-focus / list --focus)
#
# Heuristic (two complementary signals, unioned):
#   1) Block-header tag: a block whose body contains `Focus: **<focus>**`
#      declares itself part of that focus. This is the primary, authoritative
#      signal (used by ~71 blocks that carry the tag).
#   2) RESEARCH-STATE-<focus>.md citations: block numbers explicitly referenced
#      in the focus state file ([Block N] / [BN] / bloqueN). This recovers the
#      blocks a focus owns even when the block header predates the tag
#      convention or uses different wording.
# The union is returned as sorted labels. This is a best-effort mapping; the
# corpus does not carry a single machine-readable focus field per block.
# ---------------------------------------------------------------------------
def blocks_for_focus(focus: str) -> list[str]:
    focus_l = focus.lower()
    header_re = re.compile(r"Focus:\s*\*\*" + re.escape(focus) + r"\*\*", re.IGNORECASE)
    found: set[str] = set()

    # Signal 1: block-header Focus tag.
    for label, path in iter_block_files():
        try:
            head = path.read_text(encoding="utf-8")[:2000]
        except OSError:
            continue
        if header_re.search(head):
            found.add(label)

    # Signal 2: RESEARCH-STATE-<focus>.md citations.
    state = REPO_ROOT / f"RESEARCH-STATE-{focus}.md"
    if state.is_file():
        cited = refs_in_text(state.read_text(encoding="utf-8"))
        for n in cited:
            found.add(str(n))

    return sorted(found, key=label_sort_key)


def available_focuses() -> list[str]:
    out = []
    for p in sorted(REPO_ROOT.glob("RESEARCH-STATE-*.md")):
        out.append(p.name[len("RESEARCH-STATE-"):-len(".md")])
    return out


# ---------------------------------------------------------------------------
# Search corpus selection
# ---------------------------------------------------------------------------
def corpus_targets(scope: str) -> list[tuple[str, Path]]:
    """Return (display, path) pairs for the requested scope.

    For blocks, display is 'B<label>'; for docs/retros it is the relative path.
    """
    targets: list[tuple[str, Path]] = []
    if scope in ("blocks", "all"):
        for label, path in iter_block_files():
            targets.append((display_id(label), path))
    if scope in ("docs", "all"):
        for path in iter_dir_files(DOCS_DIR):
            targets.append((str(path.relative_to(REPO_ROOT)), path))
    if scope in ("retros", "all"):
        for path in iter_dir_files(RETROS_DIR):
            targets.append((str(path.relative_to(REPO_ROOT)), path))
    return targets


def run_search(pattern, scope: str, limit: int, catalog: dict[str, str]) -> int:
    """Shared engine for find/grep. `pattern` has a .search(str) method.

    Prints, grouped per file: a header line, then matching 'lineno: text'
    lines. `limit` caps the TOTAL number of matching lines printed.
    """
    shown = 0
    printed_any = False
    for display, path in corpus_targets(scope):
        if shown >= limit:
            break
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        matches = [(i + 1, ln) for i, ln in enumerate(lines) if pattern.search(ln)]
        if not matches:
            continue
        # Header: 'B<N> · <title>' for blocks, '<relpath> · <H1>' otherwise.
        if display.startswith("B"):
            label = display[1:]
            header = f"{display} · {title_for(label, catalog, path)}"
        else:
            header = f"{display} · {read_h1(path)}".rstrip(" ·")
        if printed_any:
            print()
        print(header)
        printed_any = True
        for lineno, text in matches:
            if shown >= limit:
                print(f"    ... (limit {limit} reached; use --limit to see more)")
                break
            print(f"  {lineno:>6}: {text.strip()}")
            shown += 1
    if not printed_any:
        print("No matches.")
        return 1
    return 0


# ---------------------------------------------------------------------------
# Command implementations
# ---------------------------------------------------------------------------
def cmd_find(args) -> int:
    catalog = load_catalog()
    needle = args.query.lower()

    class _Sub:  # case-insensitive substring matcher with a .search() API
        def search(self, s: str):
            return needle in s.lower()

    return run_search(_Sub(), args.scope, args.limit, catalog)


def cmd_grep(args) -> int:
    catalog = load_catalog()
    try:
        pattern = re.compile(args.regex, re.IGNORECASE)
    except re.error as e:
        print(f"Invalid regex: {e}", file=sys.stderr)
        return 2
    return run_search(pattern, args.scope, args.limit, catalog)


def _find_block_path(n: int) -> tuple[str, Path] | None:
    """Locate a numeric block file by its number."""
    for label, path in iter_block_files():
        if label not in ("1-3", "TI") and int(label) == n:
            return label, path
    return None


def cmd_show(args) -> int:
    catalog = load_catalog()
    found = _find_block_path(args.n)
    if not found:
        print(f"Block B{args.n} not found.", file=sys.stderr)
        return 1
    label, path = found

    print(f"{display_id(label)} · {title_for(label, catalog, path)}")
    print(f"  file: {path.relative_to(REPO_ROOT)}")

    # Section outline: every ## / ### heading (H1 already printed above).
    print("\n## Outline")
    any_heading = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("### "):
            print(f"    - {line[4:].strip()}")
            any_heading = True
        elif line.startswith("## "):
            print(f"  - {line[3:].strip()}")
            any_heading = True
    if not any_heading:
        print("  (no sub-headings)")

    # Connections section verbatim.
    print("\n## Connections")
    conn = extract_section(path, ("Connections", "Conexiones"))
    conn_text = "\n".join(conn).strip()
    if conn_text:
        for line in conn_text.splitlines():
            print(f"  {line}")
    else:
        print("  (no Connections section)")
    return 0


def cmd_list(args) -> int:
    catalog = load_catalog()
    focus_set = None
    if args.focus:
        focus_set = set(blocks_for_focus(args.focus))
        if not focus_set:
            print(f"No blocks found for focus '{args.focus}'.", file=sys.stderr)
            return 1
    count = 0
    for label, path in iter_block_files():
        if focus_set is not None and label not in focus_set:
            continue
        print(f"{display_id(label)} · {title_for(label, catalog, path)}")
        count += 1
    print(f"\nTotal: {count} block(s)" + (f" in focus '{args.focus}'" if args.focus else ""))
    return 0


def _marker_components(text: str) -> list[str]:
    """All marker components in text, expanding combined [A/B] tokens."""
    comps: list[str] = []
    for m in _MARKER_TOKEN_RE.finditer(text):
        for part in m.group(1).split("/"):
            part = part.strip()
            if part:
                comps.append(part)
    return comps


def cmd_by_marker(args) -> int:
    catalog = load_catalog()
    marker = args.marker.strip().strip("[]").lower()
    rows: list[tuple[str, int, Path]] = []
    for label, path in iter_block_files():
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        cnt = sum(1 for c in _marker_components(text) if c.lower() == marker)
        if cnt:
            rows.append((label, cnt, path))
    if not rows:
        print(f"No blocks contain marker [{args.marker}].")
        return 1
    for label, cnt, path in rows:
        print(f"{display_id(label)} · {cnt:>4} · {title_for(label, catalog, path)}")
    total = sum(c for _, c, _ in rows)
    print(f"\n{len(rows)} block(s), {total} occurrence(s) of [{args.marker}].")
    return 0


def cmd_by_focus(args) -> int:
    catalog = load_catalog()
    labels = blocks_for_focus(args.focus)
    if not labels:
        avail = ", ".join(available_focuses())
        print(f"No blocks found for focus '{args.focus}'.", file=sys.stderr)
        print(f"Known focuses: {avail}", file=sys.stderr)
        return 1
    by_file = {lbl: path for lbl, path in iter_block_files()}
    for label in labels:
        path = by_file.get(label)
        title = title_for(label, catalog, path) if path else "(block file not present)"
        print(f"{display_id(label)} · {title}")
    print(f"\nTotal: {len(labels)} block(s) in focus '{args.focus}'.")
    return 0


def cmd_connections(args) -> int:
    catalog = load_catalog()
    found = _find_block_path(args.n)
    if not found:
        print(f"Block B{args.n} not found.", file=sys.stderr)
        return 1
    label, path = found
    by_file = {lbl: p for lbl, p in iter_block_files()}

    print(f"{display_id(label)} · {title_for(label, catalog, path)}")

    # Forward: references inside this block's ## Connections section.
    print("\n## Forward links (this block -> others, from its Connections section)")
    conn = "\n".join(extract_section(path, ("Connections", "Conexiones")))
    fwd = sorted(n for n in refs_in_text(conn) if n != args.n)
    if fwd:
        for n in fwd:
            p = by_file.get(str(n))
            title = title_for(str(n), catalog, p) if p else "(not in corpus)"
            print(f"  B{n} · {title}")
    else:
        print("  (none)")

    # Reverse: any block anywhere that references B<N>.
    print(f"\n## Reverse links (other blocks -> B{args.n}, whole-corpus scan)")
    rev_rows: list[tuple[str, Path]] = []
    for lbl, p in iter_block_files():
        if lbl not in ("1-3", "TI") and int(lbl) == args.n:
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except OSError:
            continue
        if args.n in refs_in_text(text):
            rev_rows.append((lbl, p))
    rev_rows.sort(key=lambda t: label_sort_key(t[0]))
    if rev_rows:
        for lbl, p in rev_rows:
            print(f"  {display_id(lbl)} · {title_for(lbl, catalog, p)}")
    else:
        print("  (none)")
    return 0


def cmd_stats(args) -> int:
    blocks = iter_block_files()
    docs = iter_dir_files(DOCS_DIR)
    retros = iter_dir_files(RETROS_DIR)

    marker_counts: dict[str, int] = {}
    with_connections = 0
    for label, path in blocks:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for c in _marker_components(text):
            marker_counts[c] = marker_counts.get(c, 0) + 1
        if extract_section(path, ("Connections", "Conexiones")):
            with_connections += 1

    print("Corpus totals")
    print(f"  blocks : {len(blocks)}")
    print(f"  docs   : {len(docs)}")
    print(f"  retros : {len(retros)}")
    print(f"  focuses: {len(available_focuses())}")
    print(f"  blocks with a Connections section: {with_connections}")

    print("\nEvidence markers (occurrences across blocks)")
    # Sort by count desc, then name asc for determinism.
    for marker in sorted(marker_counts, key=lambda m: (-marker_counts[m], m)):
        print(f"  {marker:<18} {marker_counts[marker]:>6}")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="corpus-nav.py",
        description="Navigate the niagara-research knowledge corpus (blocks, docs, retros).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")

    def add_scope(p):
        p.add_argument("--in", dest="scope", choices=["blocks", "docs", "retros", "all"],
                       default="blocks", help="corpus subset to search (default: blocks)")
        p.add_argument("--limit", type=int, default=50,
                       help="max matching lines to print (default: 50)")

    p_find = sub.add_parser("find", help="full-text case-insensitive substring search")
    p_find.add_argument("query")
    add_scope(p_find)
    p_find.set_defaults(func=cmd_find)

    p_grep = sub.add_parser("grep", help="regex (re module) search")
    p_grep.add_argument("regex")
    add_scope(p_grep)
    p_grep.set_defaults(func=cmd_grep)

    p_show = sub.add_parser("show", help="H1 + outline + Connections of block B<N>")
    p_show.add_argument("n", type=int, metavar="N")
    p_show.set_defaults(func=cmd_show)

    p_list = sub.add_parser("list", help="list all blocks (from CATALOG.md)")
    p_list.add_argument("--focus", help="filter to blocks belonging to a focus")
    p_list.set_defaults(func=cmd_list)

    p_marker = sub.add_parser("by-marker", help="blocks containing an evidence marker")
    p_marker.add_argument("marker", help="e.g. INFER, CERT, CERT-hw, CERT-live")
    p_marker.set_defaults(func=cmd_by_marker)

    p_focus = sub.add_parser("by-focus", help="blocks belonging to a focus")
    p_focus.add_argument("focus")
    p_focus.set_defaults(func=cmd_by_focus)

    p_conn = sub.add_parser("connections", help="forward + reverse block links for B<N>")
    p_conn.add_argument("n", type=int, metavar="N")
    p_conn.set_defaults(func=cmd_connections)

    p_stats = sub.add_parser("stats", help="corpus totals + marker counts")
    p_stats.set_defaults(func=cmd_stats)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "command", None):
        parser.print_help()
        return 0
    return args.func(args)


if __name__ == "__main__":
    # Behave like a well-mannered CLI tool when piped into `head`, `less`, etc.
    try:
        import signal
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except (ImportError, AttributeError, ValueError):
        pass  # SIGPIPE not available on this platform
    try:
        sys.exit(main())
    except BrokenPipeError:
        sys.exit(0)
