package com.prosysopc.ua.stack.builtintypes;

import com.prosysopc.ua.stack.core.Identifiers;
import com.prosysopc.ua.stack.utils.BijectionMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public class BuiltinsMap {
   public static final Map<String, Class<?>> MAP;
   public static final Map<Class<?>, Integer> ID_MAP;
   public static final BijectionMap<NodeId, Class<?>> ID_CLASS_MAP = new BijectionMap();
   public static final List<Class<?>> SCALAR_LIST;
   public static final List<Class<?>> ARRAY_LIST;

   private BuiltinsMap() {
   }

   static {
      HashMap var0 = new HashMap();
      var0.put("http://opcfoundation.org/UA/Boolean", Boolean.class);
      var0.put("http://opcfoundation.org/UA/SByte", Byte.class);
      var0.put("http://opcfoundation.org/UA/Byte", UnsignedByte.class);
      var0.put("http://opcfoundation.org/UA/Int16", Short.class);
      var0.put("http://opcfoundation.org/UA/UInt16", UnsignedShort.class);
      var0.put("http://opcfoundation.org/UA/Int32", Integer.class);
      var0.put("http://opcfoundation.org/UA/UInt32", UnsignedInteger.class);
      var0.put("http://opcfoundation.org/UA/Int64", Long.class);
      var0.put("http://opcfoundation.org/UA/UInt64", UnsignedLong.class);
      var0.put("http://opcfoundation.org/UA/Float", Float.class);
      var0.put("http://opcfoundation.org/UA/Double", Double.class);
      var0.put("http://opcfoundation.org/UA/String", String.class);
      var0.put("http://opcfoundation.org/UA/DateTime", DateTime.class);
      var0.put("http://opcfoundation.org/UA/Guid", UUID.class);
      var0.put("http://opcfoundation.org/UA/ByteString", ByteString.class);
      var0.put("http://opcfoundation.org/UA/XmlElement", XmlElement.class);
      var0.put("http://opcfoundation.org/UA/NodeId", NodeId.class);
      var0.put("http://opcfoundation.org/UA/ExpandedNodeId", ExpandedNodeId.class);
      var0.put("http://opcfoundation.org/UA/StatusCode", StatusCode.class);
      var0.put("http://opcfoundation.org/UA/QualifiedName", QualifiedName.class);
      var0.put("http://opcfoundation.org/UA/LocalizedText", LocalizedText.class);
      var0.put("http://opcfoundation.org/UA/ExtensionObject", ExtensionObject.class);
      var0.put("http://opcfoundation.org/UA/DataValue", DataValue.class);
      var0.put("http://opcfoundation.org/UA/Variant", Variant.class);
      var0.put("http://opcfoundation.org/UA/DiagnosticInfo", DiagnosticInfo.class);
      MAP = Collections.unmodifiableMap(var0);
      HashMap var1 = new HashMap();
      var1.put(Boolean.class, 1);
      var1.put(Byte.class, 2);
      var1.put(UnsignedByte.class, 3);
      var1.put(Short.class, 4);
      var1.put(UnsignedShort.class, 5);
      var1.put(Integer.class, 6);
      var1.put(UnsignedInteger.class, 7);
      var1.put(Long.class, 8);
      var1.put(UnsignedLong.class, 9);
      var1.put(Float.class, 10);
      var1.put(Double.class, 11);
      var1.put(String.class, 12);
      var1.put(DateTime.class, 13);
      var1.put(UUID.class, 14);
      var1.put(ByteString.class, 15);
      var1.put(XmlElement.class, 16);
      var1.put(NodeId.class, 17);
      var1.put(ExpandedNodeId.class, 18);
      var1.put(StatusCode.class, 19);
      var1.put(QualifiedName.class, 20);
      var1.put(LocalizedText.class, 21);
      var1.put(ExtensionObject.class, 22);
      var1.put(DataValue.class, 23);
      var1.put(Variant.class, 24);
      var1.put(DiagnosticInfo.class, 25);
      var1.put(Boolean[].class, 1);
      var1.put(Byte[].class, 2);
      var1.put(UnsignedByte[].class, 3);
      var1.put(Short[].class, 4);
      var1.put(UnsignedShort[].class, 5);
      var1.put(Integer[].class, 6);
      var1.put(UnsignedInteger[].class, 7);
      var1.put(Long[].class, 8);
      var1.put(UnsignedLong[].class, 9);
      var1.put(Float[].class, 10);
      var1.put(Double[].class, 11);
      var1.put(String[].class, 12);
      var1.put(DateTime[].class, 13);
      var1.put(UUID[].class, 14);
      var1.put(ByteString[].class, 15);
      var1.put(XmlElement[].class, 16);
      var1.put(NodeId[].class, 17);
      var1.put(ExpandedNodeId[].class, 18);
      var1.put(StatusCode[].class, 19);
      var1.put(QualifiedName[].class, 20);
      var1.put(LocalizedText[].class, 21);
      var1.put(ExtensionObject[].class, 22);
      var1.put(DataValue[].class, 23);
      var1.put(Variant[].class, 24);
      var1.put(DiagnosticInfo[].class, 25);
      ID_MAP = Collections.unmodifiableMap(var1);
      ArrayList var2 = new ArrayList();
      var2.add(null);
      var2.add(Boolean.class);
      var2.add(Byte.class);
      var2.add(UnsignedByte.class);
      var2.add(Short.class);
      var2.add(UnsignedShort.class);
      var2.add(Integer.class);
      var2.add(UnsignedInteger.class);
      var2.add(Long.class);
      var2.add(UnsignedLong.class);
      var2.add(Float.class);
      var2.add(Double.class);
      var2.add(String.class);
      var2.add(DateTime.class);
      var2.add(UUID.class);
      var2.add(ByteString.class);
      var2.add(XmlElement.class);
      var2.add(NodeId.class);
      var2.add(ExpandedNodeId.class);
      var2.add(StatusCode.class);
      var2.add(QualifiedName.class);
      var2.add(LocalizedText.class);
      var2.add(ExtensionObject.class);
      var2.add(DataValue.class);
      var2.add(Variant.class);
      var2.add(DiagnosticInfo.class);
      SCALAR_LIST = Collections.unmodifiableList(var2);
      ArrayList var3 = new ArrayList();
      var3.add(null);
      var3.add(Boolean[].class);
      var3.add(Byte[].class);
      var3.add(UnsignedByte[].class);
      var3.add(Short[].class);
      var3.add(UnsignedShort[].class);
      var3.add(Integer[].class);
      var3.add(UnsignedInteger[].class);
      var3.add(Long[].class);
      var3.add(UnsignedLong[].class);
      var3.add(Float[].class);
      var3.add(Double[].class);
      var3.add(String[].class);
      var3.add(DateTime[].class);
      var3.add(UUID[].class);
      var3.add(ByteString[].class);
      var3.add(XmlElement[].class);
      var3.add(NodeId[].class);
      var3.add(ExpandedNodeId[].class);
      var3.add(StatusCode[].class);
      var3.add(QualifiedName[].class);
      var3.add(LocalizedText[].class);
      var3.add(ExtensionObject[].class);
      var3.add(DataValue[].class);
      var3.add(Variant[].class);
      var3.add(DiagnosticInfo[].class);
      ARRAY_LIST = Collections.unmodifiableList(var3);
      ID_CLASS_MAP.map(Identifiers.Boolean, Boolean.class);
      ID_CLASS_MAP.map(Identifiers.SByte, Byte.class);
      ID_CLASS_MAP.map(Identifiers.Byte, UnsignedByte.class);
      ID_CLASS_MAP.map(Identifiers.Int16, Short.class);
      ID_CLASS_MAP.map(Identifiers.UInt16, UnsignedShort.class);
      ID_CLASS_MAP.map(Identifiers.Int32, Integer.class);
      ID_CLASS_MAP.map(Identifiers.UInt32, UnsignedInteger.class);
      ID_CLASS_MAP.map(Identifiers.Int64, Long.class);
      ID_CLASS_MAP.map(Identifiers.UInt64, UnsignedLong.class);
      ID_CLASS_MAP.map(Identifiers.Float, Float.class);
      ID_CLASS_MAP.map(Identifiers.Double, Double.class);
      ID_CLASS_MAP.map(Identifiers.String, String.class);
      ID_CLASS_MAP.map(Identifiers.DateTime, DateTime.class);
      ID_CLASS_MAP.map(Identifiers.Guid, UUID.class);
      ID_CLASS_MAP.map(Identifiers.ByteString, ByteString.class);
      ID_CLASS_MAP.map(Identifiers.XmlElement, XmlElement.class);
      ID_CLASS_MAP.map(Identifiers.NodeId, NodeId.class);
      ID_CLASS_MAP.map(Identifiers.ExpandedNodeId, ExpandedNodeId.class);
      ID_CLASS_MAP.map(Identifiers.StatusCode, StatusCode.class);
      ID_CLASS_MAP.map(Identifiers.DiagnosticInfo, DiagnosticInfo.class);
      ID_CLASS_MAP.map(Identifiers.QualifiedName, QualifiedName.class);
      ID_CLASS_MAP.map(Identifiers.LocalizedText, LocalizedText.class);
      ID_CLASS_MAP.map(Identifiers.Structure, ExtensionObject.class);
      ID_CLASS_MAP.map(Identifiers.DataValue, DataValue.class);
      ID_CLASS_MAP.map(Identifiers.BaseDataType, Variant.class);
      ID_CLASS_MAP.map(Identifiers.DiagnosticInfo, DiagnosticInfo.class);
   }
}
